var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var en_exports = {};
__export(en_exports, {
  en: () => en
});
module.exports = __toCommonJS(en_exports);
const en = {
  common: {
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    close: "Close",
    error: "Error",
    success: "Success",
    warning: "Warning",
    yes: "Yes",
    no: "No",
    confirm: "Confirm"
  },
  themes: {
    "lightDesc": "Light appearance",
    "darkDesc": "Dark appearance",
    "highContrastDesc": "High contrast UI",
    "systemDesc": "System defaults",
    light: "Light",
    dark: "Dark",
    highContrast: "High contrast (Terminal)",
    system: "System"
  },
  tabs: {
    reports: "Reports",
    backup: "Backup & Export",
    main: "GUI Interface",
    cli: "CLI Console",
    db: "Database Explorer",
    options: "Settings",
    manual: "Manual",
    credits: "Credits & Thanks",
    rust: "Rust Source"
  },
  engine: {
    configTitle: "Engine Options & Daemons",
    configDesc: "Advanced OxyFlow microORM engine settings.",
    autoStart: "Start on system boot",
    autoPauseOnSleep: "Auto pause running timers on sleep",
    minimizeToTrayDefault: "Minimize to tray on window close",
    includePatchesInReports: "Include time patches in summaries",
    configTitle: "Engine Options & Daemons",
    configDesc: "Advanced OxyFlow microORM engine settings.",
    autoStart: "Start on system boot",
    autoPauseOnSleep: "Auto pause running timers on sleep",
    minimizeToTrayDefault: "Minimize to tray on window close",
    includePatchesInReports: "Include time patches in summaries",
    searching: "Searching for active OxyFlow engine instance...",
    connecting: "Connecting to sqlite3 database and analyzing active log rows...",
    connected: "Connected to OxyFlow Daemon",
    synced: "Engine synchronized",
    threads: "parallel tracking threads (projects run concurrently).",
    minimizeToTray: "Minimize to tray",
    sqlReset: "Reset Database (SQL Reset)"
  },
  gui: {
    newProject: "New Project",
    addTask: "Add Task",
    addSubtask: "Add Subtask",
    projectName: "Project Name",
    dashboardTitle: "Dashboard Control Panel",
    tasksAndSubtasks: "Tasks & Subtasks",
    projectTotalTime: "Project Total Time",
    activeTracker: "Active Trackers",
    stopAllThreads: "Suspend all tracking",
    selectProject: "Select project",
    noTasksInProject: "No tasks in this project yet. Add some below!",
    taskName: "Task Name",
    addSubtaskTitle: "Add New Subtask",
    addNewProject: "Add New Project",
    enterProjectName: "Enter project name",
    chooseProjectColor: "Choose project accent color",
    enterMainTaskName: "Enter main task name",
    subtaskLabel: "Subtask",
    counterLabel: "Counter",
    inProgressLabel: "In Progress",
    holidaysAndLeaves: "Holidays & Vacations",
    addHolidayLeave: "Add holiday/leave",
    reportsTitle: "Reports Logging",
    periodReport: "Periodical report",
    createdAt: "Created at",
    color: "Color",
    status: "Status",
    actions: "Actions"
  },
  settings: {
    "hardResetDesc": "Deleting all data...",
    "hardResetBtn": "Reset database",
    title: "Interface & Application Settings",
    description: "Manage global settings, language, colors, and API integrations.",
    holidaysTitle: "Holidays & Regional Settings",
    holidaysTitle: "Holidays & Regional Settings",
    addLanguage: "Add Language",
    customLanguageTitle: "Custom Language",
    customLanguageKey: "Key",
    keyLabel: "System Key",
    valueLabel: "Value",
    saveCustomTranslation: "Save",
    theme: "Interface Theme",
    destructiveZone: "Destructive Zone (Dangerous)",
    engineConfig: "Engine Settings",
    systemTray: "Minimize to System Tray Daemon by default",
    sendLogsToApi: "Send logs to external API",
    apiUrl: "API URL",
    apiToken: "API Token",
    apiMethod: "HTTP Method",
    apiMethodTitle: "API Push Method",
    apiMethodDesc: "Choose whether to use POST or PUT.",
    apiHeaders: "Custom Headers",
    apiHeadersTitle: "Advanced Headers",
    apiHeadersDesc: "Add custom JSON payload for API requests headers."
  },
  tests: {
    testsTitle: "QA Unit Tests Panel (Rust-Engine Verification)",
    runMockTests: "Run SQLite & Tauri integration tests"
  },
  help: {
    howToCompileTitle: "Compilation & Support (Tauri Wizard)",
    helpAndDocumentation: "Docs & Help Center",
    compileWizard: "Step-by-step compilation guide"
  },
  "dynamic": {
    "createdAtLabel": "Created At:",
    "archiveNoun": "Archive",
    "archive": "Archive",
    "unarchive": "Restore",
    "hideSqlitePreview": "Hide SQLite Database Preview",
    "exploreSqliteStructure": "Explore SQLite Table Structure (MicroORM)",
    "records": "records",
    "recordsPlural": "records",
    "andMoreRows": "...and {x} more rows",
    "actionsCrud": "actions (SQL CRUD)",
    "originalValue": "original",
    "dbTitle": "Tables Manager & History Audit (OxyFlow Backend)",
    "dbDesc": "View raw JSON/SQLite background database records. Thanks to timestamp logging, the calculator calculates time retrospectively, meaning you don't need to keep the application running. You can freely edit entries - their original values and change history are always preserved.",
    "tauriDriver": "Tauri SQLite Driver",
    "exportDb": "Export database",
    "entriesCrucialLabel": "Entries are crucial: time is calculated based on them. It works backward, you don't need to be logged in live.",
    "patchTableAllows": "The patch table allows patching sleep gaps or manually creating new periods to include in total work time.",
    "actionsLabel": "actions",
    "backupDesc": "Perform an immediate dump of the entire SQLite database, including project structures, logs, and patch fixes, or load a ready backup.",
    "webhookDesc": "Configure OxyFlow to send time dumps directly to an external system or database.",
    "apiAddress": "API Address",
    "bearerAuthTitle": "API Token (Bearer Auth)",
    "quickShortcuts": "Quick clickable shortcuts:",
    "settings_data": { "title": "Interface & Application Settings", "description": "Manage global settings, language, colors, and API integrations.", "holidaysTitle": "Holidays & Regional Settings" },
    "engine_data": { "configTitle": "Engine Options & Daemons", "configDesc": "Advanced OxyFlow microORM engine settings.", "autoStart": "Start on system boot", "autoPauseOnSleep": "Auto pause running timers on sleep", "minimizeToTrayDefault": "Minimize to tray on window close", "includePatchesInReports": "Include time patches in summaries" },
    "projects": "Projects",
    "nenhumProjetoAindaAdicioneUmAc": "No projects yet. Add one!",
    "registradoHoje": "Registered today",
    "todosOsRastreadoresParados": "All trackers stopped",
    "selecioneUmaTarefaAbaixoEJogue": "Select a task below and play to start.",
    "idleSQLReady": "Idle (SQL Ready)",
    "tasksFlow": "Tasks & Flow",
    "holidaysLeaves": "Holidays & Leaves",
    "summaryReports": "Summary & Reports",
    "total": "Total",
    "createAMainProjectTaskAboveThe": "Create a main project task above, then append subtasks.",
    "enterSubtaskName": "Enter subtask name...",
    "resourceDatabaseTable": "Resource database table",
    "holidaysVacations": "Holidays & Vacations",
    "rEGISTERNEWDAYOFFSQLINSERT": "REGISTER NEW DAY OFF (SQL INSERT)",
    "date": "Date",
    "type": "Type",
    "vacationLeave": "Vacation / Leave",
    "officialHoliday": "Official Holiday",
    "descriptionCause": "Description / Cause",
    "eGVibeDancingLeave": "e.g. Vibe dancing leave...",
    "save": "Save",
    "sQLiteHolidaysTableRowsMicroOR": "SQLite Holidays Table Rows (MicroORM)",
    "recordName": "Record Name",
    "scheduledDate": "Scheduled Date",
    "weekday": "Weekday",
    "actions": "Actions",
    "noEntriesFoundInputAVacationAb": "No entries found. Input a vacation above!",
    "hOLIDAY": "HOLIDAY",
    "vACATION": "VACATION",
    "deleteSQLDELETE": "Delete (SQL DELETE)",
    "sQLAnalyticsEngine": "SQL Analytics engine",
    "timeSummariesReports": "Time Summaries & Reports",
    "tODAYTOTAL": "TODAY TOTAL",
    "sQLiteLogsSumForToday": "SQLite logs sum for today",
    "wEEKTOTAL": "WEEK TOTAL",
    "fromMondayUntilNow": "From Monday until now",
    "mONTHTOTAL": "MONTH TOTAL",
    "accumulatedMonthSeconds": "Accumulated month seconds",
    "period": "Period:",
    "today": "Today",
    "week": "Week",
    "month": "Month",
    "all": "All",
    "sortBy": "Sort by:",
    "durationHighestFirst": "Duration (highest first)",
    "dateChronological": "Date (chronological)",
    "noDataInSqliteLogsForTheSelect": "No data in sqlite logs for the selected range.",
    "gRAPHICALPROJECTTIMEDISTRIBUTI": "GRAPHICAL PROJECT TIME DISTRIBUTION",
    "pLAINSQLITELOGSDUMP": "PLAIN SQLITE LOGS DUMP",
    "copiedToClipboard": "Copied to clipboard!",
    "oxyFlowMinimizedToTrayEngineKe": "OxyFlow minimized to tray. Engine keeps running.",
    "gUIClosedOxyFlowEngineLogsUISh": "GUI closed. OxyFlow engine logs UI shutdown and keeps running.",
    "mITLicenseCreditsOxyFlow": "MIT License & Credits (OxyFlow)",
    "aboutFlowCreditsMIT": "About Flow, Credits & MIT",
    "aBOUTCREATORVIBECODINGVIBE": "ABOUT CREATOR & VIBE CODING",
    "cOMPONENTCREATORSACKNOWLEDGEME": "COMPONENT CREATORS ACKNOWLEDGEMENTS",
    "forGorgeousConsistentVectorIco": "For gorgeous consistent vector icons.",
    "forCinematicReactiveStateTrans": "For cinematic reactive state transitions.",
    "forRapidElegantResponsiveUtili": "For rapid elegant responsive utility styling.",
    "forImmediateDevIterationsAndSo": "For immediate dev iterations and solid reactive state.",
    "mITLICENSE": "MIT LICENSE",
    "greatClose": "Great, close",
    "countingEngine": "Counting Engine v0.1",
    "createdForRhythm": "Created for rhythm",
    "heroDescription": "Add tasks, expand subtasks with microORM SQLite without unnecessary clicking. Manage your time simply and stylishly.",
    "noPatches": "No patches",
    "addLogManually": "Add Log Manually (INSERT SQL)",
    "selectTask": "-- Select task --",
    "noNote": "No note",
    "addLeave": "+ Add Leave (SQL INSERT)",
    "addManualPatch": "Add Manual Patch",
    "noPatchesOperatingStandard": "No patches (patch_logs). Engine operates in standard mode.",
    "selectProject": "Select project",
    "noProjects": "No projects.",
    "noTasksInProfile": "No tasks in this profile.",
    "warningResetApp": "WARNING: Are you sure you want to delete ALL logs, tasks, and projects? Holidays are not deleted. This operation cannot be undone! Type 'reset' to confirm:",
    "noActiveTimersThisMoment": "No active timers at this moment.",
    "cliStatusDesc": "Displays details of the active running timer",
    "cliCompleteDesc": "Toggles completion state of a task",
    "cliLogsDesc": "Shows log history from sqlite time_logs",
    "cliHolidaysDesc": 'Lists holidays/leaves (add holiday/leave 2026-06-15 "leave" - saves)',
    "cliReportDesc": "Generates standard and graphical reports for period",
    "cliClearDesc": "Clears console screen",
    "cliErrNoProjects": 'No projects found in SQLite. Use: addproject "Name"',
    "cliProjHeader": "\u2502  ID  \u2502 PROJECT NAME                   \u2502 TIME ELAPSED (H:M:S)   \u2502",
    "cliRequiresProjId": "Error: You must provide a project ID. Example: tasks 1",
    "cliProjNotExist": "Error: Project with ID doesn't exist.",
    "cliProjNoTasksYet": "Project does not have any tasks yet.",
    "cliProjTasksHeader": "Tasks for project",
    "cliErrSpecifyProjQuotes": 'Error: Specify project name in quotes. Example: addproject "Zouk Project"',
    "cliSuccessCreatedProj": "Success: Created project in SQLite.",
    "cliErrUsageAddTask": 'Error: Usage: addtask <proj_id> "<name>".',
    "cliSuccessAddedTask": "Success: Added task",
    "cliErrUsageAddSubtask": 'Error: Usage: addsubtask <parent_task_id> "<name>".',
    "cliSuccessAddedSubtask": "Success: Added subtask",
    "cliErrTaskNotExist": "Error: Task does not exist.",
    "cliErrTaskCompleted": "Error: Task is completed.",
    "cliTimerStarted": "Timer started for task",
    "cliNoActiveTimer": "Info: No active timer is currently running.",
    "cliTimerStopped": "Timer stopped for task",
    "cliStatusHeader": "================ ACTIVE TIMER STATUS ================",
    "cliStateIdle": "State: Idle. No active tracker running.",
    "cliUsageCompleteTask": "Error: Usage: complete <task_id>",
    "cliTaskToggled": "Task toggled successfully.",
    "cliNoLogsFound": "SQLite database: No logged time sessions found.",
    "cliLogsHeader": "\u2502 ID   \u2502 PRJ ID \u2502 STARTED AT \u2502 STATE    \u2502 DURATION               \u2502",
    "cliInvalidDateFormat": "Error: Invalid date format. Must be YYYY-MM-DD.",
    "cliNoHolidays": "SQLite database: holidays and leaves table is empty.",
    "cliHolidaysHeader": "\u2502  ID  \u2502 DATE       \u2502 TYPE        \u2502 NAME (HOLIDAY / VACATION)      \u2502",
    "cliNoLogsPeriod": "Info: No logging entries found for period",
    "cliReportTimeHeader": "TIME DURATION REPORT",
    "cliReportSysList": "--- PLAIN LIST OF SQLITE LOGS ---",
    "cliReportGraph": "--- GRAPHICAL ACTIVE PROJECTS REPRESENTATION (ASCII) ---"
  },
  manual: {
    osSelected: "Selected target OS compilation",
    title: "Compilation Manual, Shortcuts & Arch (Tauri OS Guides)",
    description: "Step-by-step guide to building production binaries and an overview of shortcuts and daemons.",
    compilationTitle: "I. Building the App Installer (Tauri CLI compilation)",
    step1: "Make sure you have Node.js installed with the package manager",
    step2: "Install Rust compilation tools",
    step3: "Enter the root folder (where your package.json is) and install packages:",
    step4: "Start the production build. Tauri will compile the JS framework and then the Rust binary:",
    step5: "Installer ready! You'll find it in:",
    shortcutsTitle: "II. Keyboard Shortcuts & System Tray Daemon",
    shortcutsDesc: 'OxyFlow relies on an embedded tauri daemon, meaning the underlying C++ and SQLite engine does not die when you close the interface (via the "X" button).',
    shortcutToggleInterface: "Toggle interface (Minimize to Tray)",
    shortcutGlobalReturn: "Fast global restore (Global Shortcut)",
    shortcutEmergencyStop: "Emergency stop all timers",
    shortcutToggleTimer: "Start / Stop current active timer",
    shortcutSystemCli: "System-level CLI"
  },
  credits: {
    description: "License, terms of service and main creator biography.",
    zoukBody: "I created this system to act as a time assistant that gracefully merges a hidden CLI engine with visual states for someone who needs pure focus. Built for someone important, inspired by my passion for dance (Brazilian Zouk) and coding."
  },
  app: {
    guiClosedTitle: "OxyFlow GUI Closed",
    guiClosedDesc: "Rust & SQLite engine is still running in the background (~8MB RAM).",
    restartGui: "Restart GUI Client",
    maximizeRestore: "OxyFlow interface window maximized.",
    stoppedThreads: "All active tracker threads have been suspended in SQLite.",
    sizeChanged: "Interface size changed to:",
    sizeSmall: "Small",
    sizeMedium: "Medium",
    sizeLarge: "Large",
    closeToTray: "Close to Tray",
    minimizeToTray: "Minimize to Tray",
    fullScreen: "Full Screen",
    searchingPid: "searching...",
    searchingEngine: "\u{1F50E} SEARCHING ENGINE...",
    activeEngine: "\u2714\uFE0F ACTIVE (SQLite)",
    subtitle: "Rust & SQLite microORM engine \u2022 Multi-project background support",
    themeDark: "Dark",
    themeLight: "Light",
    themeHighContrast: "High",
    themeSystem: "Sys",
    noTaskSelected: "Select a task first to start / stop the timer."
  }
};
