var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var es_exports = {};
__export(es_exports, {
  es: () => es
});
module.exports = __toCommonJS(es_exports);
const es = {
  "engine": {
    "configTitle": "Configuraci\xF3n del motor"
  },
  "common": {
    "cancel": "Cancelar",
    "save": "Guardar",
    "edit": "Editar",
    "delete": "Eliminar",
    "add": "A\xF1adir",
    "close": "Cerrar",
    "error": "Error",
    "success": "\xC9xito",
    "warning": "Advertencia",
    "yes": "S\xED",
    "no": "No",
    "confirm": "Confirmar"
  },
  "themes": {
    "light": "Claro",
    "dark": "Oscuro",
    "highContrast": "Alto contraste",
    "system": "Sistema"
  },
  "tabs": {
    "reports": "Informes",
    "backup": "Copia de seguridad",
    "main": "Principal",
    "db": "Base de datos",
    "options": "Opciones",
    "cli": "Consola CLI",
    "manual": "Manual",
    "credits": "Cr\xE9ditos"
  },
  "settings": {
    "addLanguage": "A\xF1adir idioma",
    "customLanguageTitle": "Idioma personalizado",
    "customLanguageKey": "Clave",
    "keyLabel": "Clave",
    "valueLabel": "Valor",
    "saveCustomTranslation": "Guardar",
    "theme": "Tema de interfaz",
    "destructiveZone": "Zona destructiva",
    "engineConfig": "Configuraci\xF3n del motor",
    "systemTray": "Minimizar en la bandeja del sistema",
    "sendLogsToApi": "Enviar registros a una API",
    "apiUrl": "URL de API",
    "apiToken": "Token de API",
    "apiMethod": "M\xE9todo HTTP",
    "apiMethodTitle": "M\xE9todo para API",
    "apiMethodDesc": "Elija POST o PUT.",
    "apiHeaders": "Cabeceras personalizadas",
    "apiHeadersTitle": "Cabeceras",
    "apiHeadersDesc": "A\xF1adir JSON de cabeceras personalizadas"
  },
  "dynamic": {
    "dbTitle": "Tables Manager & History Audit (OxyFlow Backend)",
    "dbDesc": "View raw JSON/SQLite background database records. Thanks to timestamp logging, the calculator calculates time retrospectively, meaning you don't need to keep the application running. You can freely edit entries - their original values and change history are always preserved.",
    "tauriDriver": "Tauri SQLite Driver",
    "exportDb": "Export database",
    "entriesCrucialLabel": "Entries are crucial: time is calculated based on them. It works backward, you don't need to be logged in live.",
    "patchTableAllows": "The patch table allows patching sleep gaps or manually creating new periods to include in total work time.",
    "actionsLabel": "actions",
    "backupDesc": "Perform an immediate dump of the entire SQLite database, including project structures, logs, and patch fixes, or load a ready backup.",
    "webhookDesc": "Configure OxyFlow to send time dumps directly to an external system or database.",
    "apiAddress": "API Address",
    "bearerAuthTitle": "API Token (Bearer Auth)",
    "quickShortcuts": "Quick clickable shortcuts:",
    "settings_data": { "title": "Interface & Application Settings", "description": "Manage global settings, language, colors, and API integrations.", "holidaysTitle": "Holidays & Regional Settings" },
    "engine_data": { "configTitle": "Engine Options & Daemons", "configDesc": "Advanced OxyFlow microORM engine settings.", "autoStart": "Start on system boot", "autoPauseOnSleep": "Auto pause running timers on sleep", "minimizeToTrayDefault": "Minimize to tray on window close", "includePatchesInReports": "Include time patches in summaries" },
    "countingEngine": "Counting Engine v0.1",
    "createdForRhythm": "Creado para el ritmo",
    "heroDescription": "A\xF1ada tareas, expanda subtareas con microORM SQLite sin tener que hacer clic innecesariamente. Administre su tiempo de manera sencilla y con estilo.",
    "projects": "Proyectos",
    "nenhumProjetoAindaAdicioneUmAc": "A\xFAn sin proyectos.",
    "registradoHoje": "Registrado hoy",
    "todosOsRastreadoresParados": "Todos los rastreadores detenidos",
    "selecioneUmaTarefaAbaixoEJogue": "Selecciona una tarea para comenzar.",
    "idleSQLReady": "Inactivo (SQL listo)",
    "tasksFlow": "Tareas y Flujo",
    "holidaysLeaves": "Vacaciones",
    "summaryReports": "Informes",
    "total": "Total",
    "createAMainProjectTaskAboveThe": "Crea un proyecto arriba.",
    "enterSubtaskName": "Introduce el nombre de la subtarea...",
    "resourceDatabaseTable": "Tabla de base de datos",
    "holidaysVacations": "D\xEDas festivos y vacaciones",
    "rEGISTERNEWDAYOFFSQLINSERT": "REGISTRAR NUEVO D\xCDA LIBRE",
    "date": "Fecha",
    "type": "Tipo",
    "vacationLeave": "Vacaciones",
    "officialHoliday": "D\xEDa festivo",
    "descriptionCause": "Descripci\xF3n",
    "eGVibeDancingLeave": "P. ej., fiesta...",
    "save": "Guardar",
    "sQLiteHolidaysTableRowsMicroOR": "Tabla de d\xEDas festivos",
    "recordName": "Nombre",
    "scheduledDate": "Fecha planificada",
    "weekday": "D\xEDa",
    "actions": "Acciones",
    "noEntriesFoundInputAVacationAb": "No se encontraron entradas.",
    "hOLIDAY": "FESTIVO",
    "vACATION": "VACACIONES",
    "deleteSQLDELETE": "Eliminar",
    "sQLAnalyticsEngine": "Motor de an\xE1lisis SQL",
    "timeSummariesReports": "Res\xFAmenes",
    "tODAYTOTAL": "HOY",
    "sQLiteLogsSumForToday": "Suma de hoy",
    "wEEKTOTAL": "SEMANA",
    "fromMondayUntilNow": "De lunes a ahora",
    "mONTHTOTAL": "MES",
    "accumulatedMonthSeconds": "Segundos del mes acumulados",
    "period": "Per\xEDodo:",
    "today": "Hoy",
    "week": "Semana",
    "month": "Mes",
    "all": "Todo",
    "sortBy": "Ordenar por:",
    "durationHighestFirst": "Duraci\xF3n",
    "dateChronological": "Fecha",
    "noDataInSqliteLogsForTheSelect": "Sin datos.",
    "gRAPHICALPROJECTTIMEDISTRIBUTI": "DISTRIBUCI\xD3N GR\xC1FICA",
    "pLAINSQLITELOGSDUMP": "REGISTROS SQLITE",
    "copiedToClipboard": "\xA1Copiado al portapapeles!",
    "oxyFlowMinimizedToTrayEngineKe": "Minimizado a la bandeja.",
    "gUIClosedOxyFlowEngineLogsUISh": "GUI cerrada.",
    "mITLicenseCreditsOxyFlow": "Licencia MIT y Cr\xE9ditos",
    "aboutFlowCreditsMIT": "Acerca de Flow, Cr\xE9ditos y MIT",
    "aBOUTCREATORVIBECODINGVIBE": "SOBRE EL CREADOR",
    "cOMPONENTCREATORSACKNOWLEDGEME": "AGRADECIMIENTOS",
    "forGorgeousConsistentVectorIco": "Para \xEDconos hermosos.",
    "forCinematicReactiveStateTrans": "Para animaciones.",
    "forRapidElegantResponsiveUtili": "Para estilos.",
    "forImmediateDevIterationsAndSo": "Para desarrollo.",
    "mITLICENSE": "LICENCIA MIT",
    "greatClose": "Cerrar",
    "noPatches": "Sin parches",
    "addLogManually": "A\xF1adir registro manualmente",
    "selectTask": "-- Seleccionar tarea --",
    "noNote": "Sin nota",
    "addLeave": "+ A\xF1adir ausencia",
    "addManualPatch": "A\xF1adir parche manual",
    "noPatchesOperatingStandard": "Sin parches. Modo est\xE1ndar.",
    "selectProject": "Seleccionar proyecto",
    "noProjects": "Sin proyectos.",
    "noTasksInProfile": "No hay tareas en este perfil.",
    "warningResetApp": "ADVERTENCIA: \xBFDesea eliminar TODOS los registros, tareas y proyectos? Escriba 'reset' para confirmar:",
    "noActiveTimersThisMoment": "No hay temporizadores activos en este momento.",
    "cliStatusDesc": "Muestra detalles del temporizador activo",
    "cliCompleteDesc": "Alterna el estado completado de una tarea",
    "cliLogsDesc": "Muestra historial de logs de SQLite",
    "cliHolidaysDesc": "Muestra festivos/vacaciones",
    "cliReportDesc": "Genera informes visuales",
    "cliClearDesc": "Limpia la consola",
    "cliErrNoProjects": "No se encontraron proyectos.",
    "cliProjHeader": "\u2502  ID  \u2502 NOMBRE DEL PROYECTO            \u2502 TIEMPO INVERTIDO       \u2502",
    "cliRequiresProjId": "Error: Falt\xF3 ID de proyecto.",
    "cliProjNotExist": "Error: El proyecto no existe.",
    "cliProjNoTasksYet": "El proyecto no tiene tareas a\xFAn.",
    "cliProjTasksHeader": "Tareas para proyecto",
    "cliErrSpecifyProjQuotes": "Error: Nombre del proyecto entre comillas.",
    "cliSuccessCreatedProj": "\xC9xito: Proyecto creado.",
    "cliErrUsageAddTask": "Error: Uso addtask",
    "cliSuccessAddedTask": "\xC9xito: Tarea a\xF1adida",
    "cliErrUsageAddSubtask": "Error: Uso addsubtask",
    "cliSuccessAddedSubtask": "\xC9xito: Subtarea",
    "cliErrTaskNotExist": "Error: Tarea no existe.",
    "cliErrTaskCompleted": "Error: Tarea completada.",
    "cliTimerStarted": "Temporizador iniciado para",
    "cliNoActiveTimer": "Info: Ning\xFAn temporizador activo.",
    "cliTimerStopped": "Temporizador detenido para",
    "cliStatusHeader": "== ESTADO TEMPORIZADOR ==",
    "cliStateIdle": "Estado: Inactivo",
    "cliUsageCompleteTask": "Error",
    "cliTaskToggled": "Tarea alternada",
    "cliNoLogsFound": "No se encontraron logs",
    "cliLogsHeader": "\u2502  ID  \u2502 PRJ ID \u2502 INICIADO   \u2502 ESTADO   \u2502 DURACI\xD3N               \u2502",
    "cliInvalidDateFormat": "Formato incorrecto",
    "cliNoHolidays": "Sin vacaciones",
    "cliHolidaysHeader": "\u2502  ID  \u2502 FECHA      \u2502 TIPO        \u2502 NOMBRE                         \u2502",
    "cliNoLogsPeriod": "Sin registros para per\xEDodo",
    "cliReportTimeHeader": "INFORME",
    "cliReportSysList": "--- REGISTROS ---",
    "cliReportGraph": "--- GR\xC1FICO ---"
  }
};
