const fs = require('fs');
const path = require('path');

const translations = {
  de: {
    common: { cancel: 'Abbrechen', save: 'Speichern', edit: 'Bearbeiten', delete: 'Löschen', add: 'Hinzufügen', close: 'Schließen', error: 'Fehler', success: 'Erfolg', warning: 'Warnung', yes: 'Ja', no: 'Nein', confirm: 'Bestätigen' },
    themes: { light: 'Hell', dark: 'Dunkel', highContrast: 'Hoher Kontrast', system: 'System' },
    tabs: { reports: 'Berichte', backup: 'Backup', main: 'Hauptseite', db: 'Datenbank', options: 'Optionen', cli: 'CLI-Konsole', manual: 'Handbuch', credits: 'Credits' },
    settings: { addLanguage: 'Zusätzliche Sprache', customLanguageTitle: 'Benutzerdefinierte Sprache', customLanguageKey: 'Schlüssel', keyLabel: 'Schlüssel', valueLabel: 'Wert', saveCustomTranslation: 'Speichern', theme: 'Oberflächendesign', destructiveZone: 'Zerstörerische Zone', engineConfig: 'Motor-Konfiguration', systemTray: 'In die Taskleiste minimieren', sendLogsToApi: 'Logs an externe API senden', apiUrl: 'API URL', apiToken: 'API Token', apiMethod: 'HTTP Methode', apiMethodTitle: 'API Push Methode', apiMethodDesc: 'Wählen Sie zwischen POST oder PUT.', apiHeaders: 'Benutzerdefinierte Header', apiHeadersTitle: 'Erweiterte Header', apiHeadersDesc: 'Fügen Sie benutzerdefinierte JSON-Header für den API-Push hinzu' },
    dynamic: {
      countingEngine: 'Counting Engine v0.1', createdForRhythm: 'Für den Rhythmus gemacht', heroDescription: 'Fügen Sie Aufgaben hinzu, erweitern Sie Unteraufgaben mit microORM SQLite, ohne unnötiges Klicken. Verwalten Sie Ihre Zeit einfach und stilvoll.',
      projects: 'Projekte', nenhumProjetoAindaAdicioneUmAc: 'Noch keine Projekte.', registradoHoje: 'Heute registriert', todosOsRastreadoresParados: 'Alle Tracker gestoppt', selecioneUmaTarefaAbaixoEJogue: 'Wählen Sie eine Aufgabe zum Starten.', idleSQLReady: 'Leerlauf (SQL Bereit)', tasksFlow: 'Aufgaben & Flow', holidaysLeaves: 'Urlaub', summaryReports: 'Berichte', total: 'Gesamt', createAMainProjectTaskAboveThe: 'Erstellen Sie ein Hauptprojekt darüber.', enterSubtaskName: 'Unteraufgabe eingeben...', resourceDatabaseTable: 'Ressourcen-Datenbanktabelle', holidaysVacations: 'Feiertage & Urlaub', rEGISTERNEWDAYOFFSQLINSERT: 'NEUEN URLAUB REGISTRIEREN', date: 'Datum', type: 'Typ', vacationLeave: 'Urlaub', officialHoliday: 'Feiertag', descriptionCause: 'Beschreibung', eGVibeDancingLeave: 'z.B. Vibe-Dancing...', save: 'Speichern', sQLiteHolidaysTableRowsMicroOR: 'Feiertage-Tabelle', recordName: 'Name', scheduledDate: 'Geplantes Datum', weekday: 'Wochentag', actions: 'Aktionen', noEntriesFoundInputAVacationAb: 'Keine Einträge gefunden.', hOLIDAY: 'FEIERTAG', vACATION: 'URLAUB', deleteSQLDELETE: 'Löschen', sQLAnalyticsEngine: 'SQL-Analysemaschine', timeSummariesReports: 'Zusammenfassungen', tODAYTOTAL: 'HEUTE', sQLiteLogsSumForToday: 'Summe für heute', wEEKTOTAL: 'WOCHE', fromMondayUntilNow: 'Von Montag bis jetzt', mONTHTOTAL: 'MONAT', accumulatedMonthSeconds: 'Akkumulierte Monatssekunden', period: 'Periode:', today: 'Heute', week: 'Woche', month: 'Monat', all: 'Alle', sortBy: 'Sortieren nach:', durationHighestFirst: 'Dauer', dateChronological: 'Datum', noDataInSqliteLogsForTheSelect: 'Keine Daten.', gRAPHICALPROJECTTIMEDISTRIBUTI: 'GRAFISCHE ZEITVERTEILUNG', pLAINSQLITELOGSDUMP: 'SQLITE-LOGS', copiedToClipboard: 'In die Zwischenablage kopiert!', oxyFlowMinimizedToTrayEngineKe: 'In die Taskleiste minimiert.', gUIClosedOxyFlowEngineLogsUISh: 'GUI geschlossen.', mITLicenseCreditsOxyFlow: 'MIT-Lizenz & Credits', aboutFlowCreditsMIT: 'Über Flow, Credits & MIT', aBOUTCREATORVIBECODINGVIBE: 'ÜBER DEN ERSTELLER', cOMPONENTCREATORSACKNOWLEDGEME: 'DANKSAGUNGEN', forGorgeousConsistentVectorIco: 'Für wunderschöne Icons.', forCinematicReactiveStateTrans: 'Für Animationen.', forRapidElegantResponsiveUtili: 'Für Styling.', forImmediateDevIterationsAndSo: 'Für Entwicklung.', mITLICENSE: 'MIT-LIZENZ', greatClose: 'Schließen'
    }
  },
  es: {
    common: { cancel: 'Cancelar', save: 'Guardar', edit: 'Editar', delete: 'Eliminar', add: 'Añadir', close: 'Cerrar', error: 'Error', success: 'Éxito', warning: 'Advertencia', yes: 'Sí', no: 'No', confirm: 'Confirmar' },
    themes: { light: 'Claro', dark: 'Oscuro', highContrast: 'Alto contraste', system: 'Sistema' },
    tabs: { reports: 'Informes', backup: 'Copia de seguridad', main: 'Principal', db: 'Base de datos', options: 'Opciones', cli: 'Consola CLI', manual: 'Manual', credits: 'Créditos' },
    settings: { addLanguage: 'Añadir idioma', customLanguageTitle: 'Idioma personalizado', customLanguageKey: 'Clave', keyLabel: 'Clave', valueLabel: 'Valor', saveCustomTranslation: 'Guardar', theme: 'Tema de interfaz', destructiveZone: 'Zona destructiva', engineConfig: 'Configuración del motor', systemTray: 'Minimizar en la bandeja del sistema', sendLogsToApi: 'Enviar registros a una API', apiUrl: 'URL de API', apiToken: 'Token de API', apiMethod: 'Método HTTP', apiMethodTitle: 'Método para API', apiMethodDesc: 'Elija POST o PUT.', apiHeaders: 'Cabeceras personalizadas', apiHeadersTitle: 'Cabeceras', apiHeadersDesc: 'Añadir JSON de cabeceras personalizadas' },
    dynamic: {
      countingEngine: 'Counting Engine v0.1', createdForRhythm: 'Creado para el ritmo', heroDescription: 'Añada tareas, expanda subtareas con microORM SQLite sin tener que hacer clic innecesariamente. Administre su tiempo de manera sencilla y con estilo.',
      projects: 'Proyectos', nenhumProjetoAindaAdicioneUmAc: 'Aún sin proyectos.', registradoHoje: 'Registrado hoy', todosOsRastreadoresParados: 'Todos los rastreadores detenidos', selecioneUmaTarefaAbaixoEJogue: 'Selecciona una tarea para comenzar.', idleSQLReady: 'Inactivo (SQL listo)', tasksFlow: 'Tareas y Flujo', holidaysLeaves: 'Vacaciones', summaryReports: 'Informes', total: 'Total', createAMainProjectTaskAboveThe: 'Crea un proyecto arriba.', enterSubtaskName: 'Introduce el nombre de la subtarea...', resourceDatabaseTable: 'Tabla de base de datos', holidaysVacations: 'Días festivos y vacaciones', rEGISTERNEWDAYOFFSQLINSERT: 'REGISTRAR NUEVO DÍA LIBRE', date: 'Fecha', type: 'Tipo', vacationLeave: 'Vacaciones', officialHoliday: 'Día festivo', descriptionCause: 'Descripción', eGVibeDancingLeave: 'P. ej., fiesta...', save: 'Guardar', sQLiteHolidaysTableRowsMicroOR: 'Tabla de días festivos', recordName: 'Nombre', scheduledDate: 'Fecha planificada', weekday: 'Día', actions: 'Acciones', noEntriesFoundInputAVacationAb: 'No se encontraron entradas.', hOLIDAY: 'FESTIVO', vACATION: 'VACACIONES', deleteSQLDELETE: 'Eliminar', sQLAnalyticsEngine: 'Motor de análisis SQL', timeSummariesReports: 'Resúmenes', tODAYTOTAL: 'HOY', sQLiteLogsSumForToday: 'Suma de hoy', wEEKTOTAL: 'SEMANA', fromMondayUntilNow: 'De lunes a ahora', mONTHTOTAL: 'MES', accumulatedMonthSeconds: 'Segundos del mes acumulados', period: 'Período:', today: 'Hoy', week: 'Semana', month: 'Mes', all: 'Todo', sortBy: 'Ordenar por:', durationHighestFirst: 'Duración', dateChronological: 'Fecha', noDataInSqliteLogsForTheSelect: 'Sin datos.', gRAPHICALPROJECTTIMEDISTRIBUTI: 'DISTRIBUCIÓN GRÁFICA', pLAINSQLITELOGSDUMP: 'REGISTROS SQLITE', copiedToClipboard: '¡Copiado al portapapeles!', oxyFlowMinimizedToTrayEngineKe: 'Minimizado a la bandeja.', gUIClosedOxyFlowEngineLogsUISh: 'GUI cerrada.', mITLicenseCreditsOxyFlow: 'Licencia MIT y Créditos', aboutFlowCreditsMIT: 'Acerca de Flow, Créditos y MIT', aBOUTCREATORVIBECODINGVIBE: 'SOBRE EL CREADOR', cOMPONENTCREATORSACKNOWLEDGEME: 'AGRADECIMIENTOS', forGorgeousConsistentVectorIco: 'Para íconos hermosos.', forCinematicReactiveStateTrans: 'Para animaciones.', forRapidElegantResponsiveUtili: 'Para estilos.', forImmediateDevIterationsAndSo: 'Para desarrollo.', mITLICENSE: 'LICENCIA MIT', greatClose: 'Cerrar'
    }
  },
  fr: {
    common: { cancel: 'Annuler', save: 'Enregistrer', edit: 'Modifier', delete: 'Supprimer', add: 'Ajouter', close: 'Fermer', error: 'Erreur', success: 'Succès', warning: 'Avertissement', yes: 'Oui', no: 'Non', confirm: 'Confirmer' },
    themes: { light: 'Clair', dark: 'Sombre', highContrast: 'Contraste élevé', system: 'Système' },
    tabs: { reports: 'Rapports', backup: 'Sauvegarde', main: 'Principal', db: 'Base de données', options: 'Options', cli: 'Console CLI', manual: 'Manuel', credits: 'Créditos' },
    settings: { addLanguage: 'Ajouter une langue', customLanguageTitle: 'Langue personnalisée', customLanguageKey: 'Clé', keyLabel: 'Clé', valueLabel: 'Valeur', saveCustomTranslation: 'Enregistrer', theme: 'Thème de l\'interface', destructiveZone: 'Zone destructrice', engineConfig: 'Configuration du moteur', systemTray: 'Réduire dans la zone de notification', sendLogsToApi: 'Envoyer les journaux à l\'API', apiUrl: 'URL de l\'API', apiToken: 'Jeton de l\'API', apiMethod: 'Méthode HTTP', apiMethodTitle: 'Méthode d\'action API', apiMethodDesc: 'Choisissez POST ou PUT.', apiHeaders: 'En-têtes', apiHeadersTitle: 'Têtes personnalisées', apiHeadersDesc: 'Ajoutez du JSON pour l\'en-tête API' },
    dynamic: {
      countingEngine: 'Counting Engine v0.1', createdForRhythm: 'Créé pour le rythme', heroDescription: 'Ajoutez des tâches, développez des sous-tâches avec microORM SQLite sans clics inutiles. Gérez votre temps simplement et avec style.',
      projects: 'Projets', nenhumProjetoAindaAdicioneUmAc: 'Pas de projets.', registradoHoje: 'Enregistré aujourd\'hui', todosOsRastreadoresParados: 'Tous les traceurs arrêtés', selecioneUmaTarefaAbaixoEJogue: 'Sélectionnez une tâche pour démarrer.', idleSQLReady: 'Inactif (SQL prêt)', tasksFlow: 'Tâches & Flux', holidaysLeaves: 'Congés', summaryReports: 'Rapports', total: 'Total', createAMainProjectTaskAboveThe: 'Créez un projet au-dessus.', enterSubtaskName: 'Entrez le nom de la sous-tâche...', resourceDatabaseTable: 'Table de la base de données', holidaysVacations: 'Jours fériés & Vacances', rEGISTERNEWDAYOFFSQLINSERT: 'ENREGISTRER UN NOUVEAU JOUR DE CONGÉ', date: 'Date', type: 'Type', vacationLeave: 'Vacances', officialHoliday: 'Jour férié', descriptionCause: 'Description', eGVibeDancingLeave: 'Ex. vacances...', save: 'Enregistrer', sQLiteHolidaysTableRowsMicroOR: 'Table des congés', recordName: 'Nom', scheduledDate: 'Date prévue', weekday: 'Jour', actions: 'Actions', noEntriesFoundInputAVacationAb: 'Aucune entrée.', hOLIDAY: 'JOUR FÉRIÉ', vACATION: 'VACACIONES', deleteSQLDELETE: 'Supprimer', sQLAnalyticsEngine: 'Moteur d\'analyse SQL', timeSummariesReports: 'Résumés', tODAYTOTAL: 'AUJOURD\'HUI', sQLiteLogsSumForToday: 'Total d\'aujourd\'hui', wEEKTOTAL: 'SEMAINE', fromMondayUntilNow: 'De lundi à maintenant', mONTHTOTAL: 'MOIS', accumulatedMonthSeconds: 'Secondes accumulées ce mois', period: 'Période :', today: 'Aujourd\'hui', week: 'Semaine', month: 'Mois', all: 'Tout', sortBy: 'Trier par :', durationHighestFirst: 'Durée', dateChronological: 'Date', noDataInSqliteLogsForTheSelect: 'Pas de données.', gRAPHICALPROJECTTIMEDISTRIBUTI: 'DISTRIBUTION GRAPHIQUE', pLAINSQLITELOGSDUMP: 'JOURNAUX SQLITE', copiedToClipboard: 'Copié !', oxyFlowMinimizedToTrayEngineKe: 'Réduit dans la zone de notification.', gUIClosedOxyFlowEngineLogsUISh: 'Interface GUI fermée.', mITLicenseCreditsOxyFlow: 'Licence MIT & Créditos', aboutFlowCreditsMIT: 'A propos de Flow, crédits & MIT', aBOUTCREATORVIBECODINGVIBE: 'À PROPOS DU CRÉATEUR', cOMPONENTCREATORSACKNOWLEDGEME: 'REMERCIEMENTS', forGorgeousConsistentVectorIco: 'Pour de superbes icônes.', forCinematicReactiveStateTrans: 'Pour de belles animations.', forRapidElegantResponsiveUtili: 'Pour le style.', forImmediateDevIterationsAndSo: 'Pour le développement.', mITLICENSE: 'LICENCE MIT', greatClose: 'Fermer'
    }
  },
  'pt-br': {
    common: { cancel: 'Cancelar', save: 'Salvar', edit: 'Editar', delete: 'Deletar', add: 'Adicionar', close: 'Fechar', error: 'Erro', success: 'Sucesso', warning: 'Aviso', yes: 'Sim', no: 'Não', confirm: 'Confirmar' },
    themes: { light: 'Claro', dark: 'Escuro', highContrast: 'Alto Contraste', system: 'Sistema' },
    tabs: { reports: 'Relatórios', backup: 'Backup', main: 'Principal', db: 'Banco de Dados', options: 'Opções', cli: 'Console CLI', manual: 'Manual', credits: 'Créditos' },
    settings: { addLanguage: 'Adicionar Idioma', customLanguageTitle: 'Idioma Personalizado', customLanguageKey: 'Chave', keyLabel: 'Chave', valueLabel: 'Valor', saveCustomTranslation: 'Salvar', theme: 'Tema da Interface', destructiveZone: 'Zona Destrutiva', engineConfig: 'Configuração do Motor', systemTray: 'Minimizar para a bandeja do sistema', sendLogsToApi: 'Enviar logs para API externa', apiUrl: 'URL da API', apiToken: 'Token da API', apiMethod: 'Método HTTP', apiMethodTitle: 'Método de envio da API', apiMethodDesc: 'Marque para PUT, desmarque para POST.', apiHeaders: 'Cabeçalhos', apiHeadersTitle: 'Cabeçalhos personalizados', apiHeadersDesc: 'JSON Headers' },
    dynamic: {
      countingEngine: 'Counting Engine v0.1', createdForRhythm: 'Criado para o ritmo', heroDescription: 'Adicione tarefas, expanda subtarefas com microORM SQLite sem cliques desnecessários. Gerencie seu tempo de forma simples e com estilo.',
      projects: 'Projetos', nenhumProjetoAindaAdicioneUmAc: 'Nenhum projeto ainda.', registradoHoje: 'Registrado hoje', todosOsRastreadoresParados: 'Todos os rastreadores parados', selecioneUmaTarefaAbaixoEJogue: 'Selecione uma tarefa para começar.', idleSQLReady: 'Inativo (SQL Pronto)', tasksFlow: 'Tarefas e Fluxo', holidaysLeaves: 'Férias', summaryReports: 'Relatórios', total: 'Total', createAMainProjectTaskAboveThe: 'Crie um projeto acima.', enterSubtaskName: 'Digite o nome da subtarefa...', resourceDatabaseTable: 'Tabela do banco de dados', holidaysVacations: 'Feriados e Férias', rEGISTERNEWDAYOFFSQLINSERT: 'REGISTRAR NOVO DIA DE FOLGA', date: 'Data', type: 'Tipo', vacationLeave: 'Férias', officialHoliday: 'Feriado', descriptionCause: 'Descrição', eGVibeDancingLeave: 'Ex: Festa...', save: 'Salvar', sQLiteHolidaysTableRowsMicroOR: 'Tabela de feriados', recordName: 'Nome', scheduledDate: 'Data agendada', weekday: 'Dia da semana', actions: 'Ações', noEntriesFoundInputAVacationAb: 'Nenhuma entrada encontrada.', hOLIDAY: 'FERIADO', vACATION: 'FÉRIAS', deleteSQLDELETE: 'Deletar', sQLAnalyticsEngine: 'Motor de análise SQL', timeSummariesReports: 'Resumos', tODAYTOTAL: 'HOJE', sQLiteLogsSumForToday: 'Soma de hoje', wEEKTOTAL: 'SEMANA', fromMondayUntilNow: 'De segunda até agora', mONTHTOTAL: 'MÊS', accumulatedMonthSeconds: 'Segundos do mês acumulados', period: 'Período:', today: 'Hoje', week: 'Semana', month: 'Mês', all: 'Tudo', sortBy: 'Ordenar por:', durationHighestFirst: 'Duração', dateChronological: 'Data', noDataInSqliteLogsForTheSelect: 'Sem dados.', gRAPHICALPROJECTTIMEDISTRIBUTI: 'DISTRIBUIÇÃO GRÁFICA', pLAINSQLITELOGSDUMP: 'LOGS DO SQLITE', copiedToClipboard: 'Copiado para a área de transferência!', oxyFlowMinimizedToTrayEngineKe: 'Minimizado.', gUIClosedOxyFlowEngineLogsUISh: 'GUI fechada.', mITLicenseCreditsOxyFlow: 'Licença MIT e Créditos', aboutFlowCreditsMIT: 'Sobre o Flow, Créditos e MIT', aBOUTCREATORVIBECODINGVIBE: 'SOBRE O CRIADOR', cOMPONENTCREATORSACKNOWLEDGEME: 'AGRADECIMENTOS', forGorgeousConsistentVectorIco: 'Para ícones lindos.', forCinematicReactiveStateTrans: 'Para animações.', forRapidElegantResponsiveUtili: 'Para estilos.', forImmediateDevIterationsAndSo: 'Para desenvolvimento.', mITLICENSE: 'LICENÇA MIT', greatClose: 'Fechar'
    }
  }
};

for (const lang of Object.keys(translations)) {
  const content = "export const " + (lang === 'pt-br' ? 'ptBr' : lang) + " = " + JSON.stringify(translations[lang], null, 2) + ";";
  fs.writeFileSync("src/utils/i18n/" + lang + ".ts", content);
}

let i18n = fs.readFileSync('src/utils/i18n.ts', 'utf8');
if (!i18n.includes("import { de }")) {
  i18n = i18n.replace("import { pl } from './i18n/pl';", "import { pl } from './i18n/pl';\nimport { de } from './i18n/de';\nimport { es } from './i18n/es';\nimport { ptBr } from './i18n/pt-br';\nimport { fr } from './i18n/fr';");
  i18n = i18n.replace("export const dictionaries = { en, pl };", "export const dictionaries = { en, pl, de, es, 'pt-br': ptBr, fr };");
  fs.writeFileSync('src/utils/i18n.ts', i18n);
}

let en = fs.readFileSync('src/utils/i18n/en.ts', 'utf8');
en = en.replace("mITLICENSE: 'MIT LICENSE',", "mITLICENSE: 'MIT LICENSE',\n    countingEngine: 'Counting Engine v0.1',\n    createdForRhythm: 'Created for rhythm',\n    heroDescription: 'Add tasks, expand subtasks with microORM SQLite without unnecessary clicking. Manage your time simply and stylishly.',");
en = en.replace(/settings: \{[\s\S]*?\},/, "settings: { addLanguage: 'Add Language', customLanguageTitle: 'Custom Language', customLanguageKey: 'Key', keyLabel: 'System Key', valueLabel: 'Value', saveCustomTranslation: 'Save', theme: 'Interface Theme', destructiveZone: 'Destructive Zone (Dangerous)', engineConfig: 'Engine Settings', systemTray: 'Minimize to System Tray Daemon by default', sendLogsToApi: 'Send logs to external API', apiUrl: 'API URL', apiToken: 'API Token', apiMethod: 'HTTP Method', apiMethodTitle: 'API Push Method', apiMethodDesc: 'Choose whether to use POST or PUT.', apiHeaders: 'Custom Headers', apiHeadersTitle: 'Advanced Headers', apiHeadersDesc: 'Add custom JSON payload for API requests headers.' },");
fs.writeFileSync('src/utils/i18n/en.ts', en);

let pl = fs.readFileSync('src/utils/i18n/pl.ts', 'utf8');
pl = pl.replace("mITLICENSE: 'Licencja MIT',", "mITLICENSE: 'Licencja MIT',\n    countingEngine: 'Counting Engine v0.1',\n    createdForRhythm: 'Stworzone dla rytmu',\n    heroDescription: 'Dodawaj zadania, rozwijaj podzadania z mikroORM SQLite bez zbędnego klikania. Zarządzaj czasem prosto i stylowo.',");
pl = pl.replace(/settings: \{[\s\S]*?\},/, "settings: { addLanguage: 'Dodaj język', customLanguageTitle: 'Własny język', customLanguageKey: 'Klucz', keyLabel: 'Klucz systemowy', valueLabel: 'Wartość', saveCustomTranslation: 'Zapisz', theme: 'Motyw interfejsu', destructiveZone: 'Strefa destrukcji', engineConfig: 'Ustawienia silnika', systemTray: 'Zminimalizuj do paska zadań', sendLogsToApi: 'Wyślij do zewnętrznego API', apiUrl: 'Adres URL API', apiToken: 'Token uwierzytelniający API', apiMethod: 'Metoda HTTP', apiMethodTitle: 'Metoda wysyłania (Push)', apiMethodDesc: 'Wybierz pomiędzy protokołami POST lub PUT.', apiHeaders: 'Niestandardowe Nagłówki', apiHeadersTitle: 'Zawansowane Nagłówki (Headers)', apiHeadersDesc: 'Uzupełnij odpowiedni poprawny ciąg JSON, zostanie załączony do headers api.' },");
fs.writeFileSync('src/utils/i18n/pl.ts', pl);
