const fs = require('fs');
const path = require('path');

const de = {
  common: {
    cancel: 'Abbrechen',
    save: 'Speichern',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    add: 'Hinzufügen',
    close: 'Schließen',
    error: 'Fehler',
    success: 'Erfolg',
    warning: 'Warnung',
    yes: 'Ja',
    no: 'Nein',
    confirm: 'Bestätigen'
  },
  themes: {
    light: 'Hell',
    dark: 'Dunkel',
    highContrast: 'Hoher Kontrast (Terminal)',
    system: 'System'
  },
  tabs: {
    reports: 'Berichte',
    backup: 'Backup & Export',
    main: 'GUI-Schnittstelle',
    cli: 'CLI-Konsole',
    db: 'Datenbank-Explorer',
    options: 'Einstellungen',
    manual: 'Handbuch',
    credits: 'Credits & Dank',
    rust: 'Rust-Quellcode'
  },
  engine: {
    configTitle: "Motor-Optionen & Dämons",
    configDesc: "Erweiterte OxyFlow microORM Motor-Einstellungen.",
    autoStart: "Beim Systemstart ausführen",
    autoPauseOnSleep: "Aktive Timer bei Ruhezustand automatisch anhalten",
    minimizeToTrayDefault: "Beim Schließen des Fensters in die Taskleiste minimieren",
    includePatchesInReports: "Zeit-Patches in Zusammenfassungen einbeziehen",
    searching: 'Suche nach aktiver OxyFlow-Motorinstanz...',
    connecting: 'Verbindung zur sqlite3-Datenbank und Analyse der aktiven Protokollzeilen...',
    connected: 'Mit OxyFlow-Dämon verbunden',
    synced: 'Motor synchronisiert',
    threads: 'parallele Tracking-Threads (Projekte laufen gleichzeitig).',
    minimizeToTray: 'In Taskleiste minimieren',
    sqlReset: 'Datenbank zurücksetzen (SQL Reset)'
  },
  gui: {
    newProject: 'Neues Projekt',
    addTask: 'Aufgabe hinzufügen',
    addSubtask: 'Unteraufgabe hinzufügen',
    projectName: 'Projektname',
    dashboardTitle: 'Dashboard-Bedienfeld',
    tasksAndSubtasks: 'Aufgaben & Unteraufgaben',
    projectTotalTime: 'Gesamtzeit des Projekts',
    activeTracker: 'Aktive Tracker',
    stopAllThreads: 'Alle Verfolgungen anhalten',
    selectProject: 'Projekt auswählen',
    noTasksInProject: 'Noch keine Aufgaben in diesem Projekt. Fügen Sie unten einige hinzu!',
    taskName: 'Aufgabenname',
    addSubtaskTitle: 'Neue Unteraufgabe hinzufügen',
    addNewProject: 'Neues Projekt hinzufügen',
    enterProjectName: 'Projektnamen eingeben',
    chooseProjectColor: 'Projekt-Akzentfarbe wählen',
    enterMainTaskName: 'Name der Hauptaufgabe eingeben',
    subtaskLabel: 'Unteraufgabe',
    counterLabel: 'Zähler',
    inProgressLabel: 'In Bearbeitung',
    holidaysAndLeaves: 'Feiertage & Urlaub',
    addHolidayLeave: 'Feiertag/Urlaub hinzufügen',
    reportsTitle: 'Berichtsprotokollierung',
    periodReport: 'Periodischer Bericht',
    createdAt: 'Erstellt am',
    color: 'Farbe',
    status: 'Status',
    actions: 'Aktionen'
  },
  settings: {
    title: "Schnittstellen- & Anwendungseinstellungen",
    description: "Verwalten Sie globale Einstellungen, Sprache, Farben und API-Integrationen.",
    holidaysTitle: "Feiertage & Regionale Einstellungen",
    addLanguage: 'Sprache hinzufügen',
    customLanguageTitle: 'Benutzerdefinierte Sprache',
    customLanguageKey: 'Schlüssel',
    keyLabel: 'Systemschlüssel',
    valueLabel: 'Wert',
    saveCustomTranslation: 'Speichern',
    theme: 'Oberflächendesign',
    destructiveZone: 'Zerstörerische Zone (Gefährlich)',
    engineConfig: 'Motoreinstellungen',
    systemTray: 'Standardmäßig in System Tray Dämon minimieren',
    sendLogsToApi: 'Protokolle an externe API senden',
    apiUrl: 'API URL',
    apiToken: 'API Token',
    apiMethod: 'HTTP-Methode',
    apiMethodTitle: 'API-Push-Methode',
    apiMethodDesc: 'Wählen Sie, ob POST oder PUT verwendet werden soll.',
    apiHeaders: 'Benutzerdefinierte Header',
    apiHeadersTitle: 'Erweiterte Header',
    apiHeadersDesc: 'Fügen Sie benutzerdefinierte JSON-Nutzdaten für API-Anfrageheader hinzu.'
  },
  tests: {
    testsTitle: 'QA Unit Tests Panel (Rust-Motor-Verifizierung)',
    runMockTests: 'Führen Sie SQLite- & Tauri-Integrationstests aus'
  },
  help: {
    howToCompileTitle: 'Kompilierung & Support (Tauri-Assistent)',
    helpAndDocumentation: 'Dokumentation & Hilfe-Center',
    compileWizard: 'Schritt-für-Schritt-Kompilierungsanleitung'
  },
  dynamic: {
    dbTitle: "Tabellen-Manager & Historien-Audit (OxyFlow-Backend)",
    dbDesc: "Betrachten Sie rohe JSON/SQLite-Hintergrunddatenbankaufzeichnungen. Dank der Zeitstempel-Protokollierung berechnet der Rechner die Zeit rückwirkend, was bedeutet, dass Sie die Anwendung nicht ständig ausführen müssen. Sie können Einträge frei bearbeiten - ihre ursprünglichen Werte und die Änderungshistorie bleiben immer erhalten.",
    tauriDriver: "Tauri SQLite-Treiber",
    exportDb: "Datenbank exportieren",
    entriesCrucialLabel: "Einträge sind entscheidend: Auf ihrer Basis wird die Zeit berechnet. Es funktioniert rückwirkend, Sie müssen nicht live angemeldet sein.",
    patchTableAllows: "Die Patch-Tabelle ermöglicht das Patchen von Schlafunterbrechungen oder das manuelle Erstellen neuer Zeiträume, um sie in die Gesamtarbeitszeit einzubeziehen.",
    actionsLabel: "Aktionen",
    backupDesc: "Führen Sie einen sofortigen Dump der gesamten SQLite-Datenbank durch, einschließlich Projektstrukturen, Protokollen und Patch-Korrekturen, oder laden Sie ein fertiges Backup.",
    webhookDesc: "Konfigurieren Sie OxyFlow so, dass Zeit-Dumps direkt an ein externes System oder eine externe Datenbank gesendet werden.",
    apiAddress: "API-Adresse",
    bearerAuthTitle: "API-Token (Bearer Auth)",
    quickShortcuts: "Schnelle anklickbare Verknüpfungen:",
    countingEngine: "Zähl-Motor v0.1",
    createdForRhythm: "Für den Rhythmus gemacht",
    heroDescription: "Fügen Sie Aufgaben hinzu, erweitern Sie Unteraufgaben mit microORM SQLite ohne unnötiges Klicken. Verwalten Sie Ihre Zeit einfach und stilvoll.",
    projects: "Projekte",
    nenhumProjetoAindaAdicioneUmAc: "Noch keine Projekte. Fügen Sie eins hinzu!",
    registradoHoje: "Heute registriert",
    todosOsRastreadoresParados: "Alle Tracker gestoppt",
    selecioneUmaTarefaAbaixoEJogue: "Wählen Sie unten eine Aufgabe aus und drücken Sie Play zum Starten.",
    idleSQLReady: "Leerlauf (SQL Bereit)",
    tasksFlow: "Aufgaben & Fluss",
    holidaysLeaves: "Urlaub & Feiertage",
    summaryReports: "Zusammenfassung & Berichte",
    total: "Gesamt",
    createAMainProjectTaskAboveThe: "Erstellen Sie oben eine Hauptprojektaufgabe und fügen Sie dann Unteraufgaben hinzu.",
    enterSubtaskName: "Unteraufgabenname eingeben...",
    resourceDatabaseTable: "Ressourcen-Datenbanktabelle",
    holidaysVacations: "Feiertage & Urlaub",
    "rEGISTERNEWDAYOFFSQLINSERT": "NEUEN URLAUB REGISTRIEREN (SQL INSERT)",
    date: "Datum",
    type: "Typ",
    vacationLeave: "Urlaub / Freistellung",
    officialHoliday: "Gesetzlicher Feiertag",
    descriptionCause: "Beschreibung / Grund",
    eGVibeDancingLeave: "z.B. Vibe-Tanzurlaub...",
    save: "Speichern",
    sQLiteHolidaysTableRowsMicroOR: "SQLite Feiertage Tabellenzeilen (MicroORM)",
    "recordName": "Name des Datensatzes",
    scheduledDate: "Geplantes Datum",
    weekday: "Wochentag",
    actions: "Aktionen",
    noEntriesFoundInputAVacationAb: "Keine Einträge gefunden. Geben Sie oben einen Urlaub ein!",
    hOLIDAY: "FEIERTAG",
    vACATION: "URLAUB",
    deleteSQLDELETE: "Löschen (SQL DELETE)",
    sQLAnalyticsEngine: "SQL-Analyse-Motor",
    timeSummariesReports: "Zeitzusammenfassungen & Berichte",
    tODAYTOTAL: "HEUTE GESAMT",
    sQLiteLogsSumForToday: "SQLite-Protokollsumme für heute",
    wEEKTOTAL: "WOCHE GESAMT",
    fromMondayUntilNow: "Von Montag bis jetzt",
    mONTHTOTAL: "MONAT GESAMT",
    accumulatedMonthSeconds: "Akkumulierte Monatssekunden",
    period: "Zeitraum:",
    today: "Heute",
    week: "Woche",
    month: "Monat",
    all: "Alle",
    sortBy: "Sortieren nach:",
    durationHighestFirst: "Dauer (höchste zuerst)",
    dateChronological: "Datum (chronologisch)",
    noDataInSqliteLogsForTheSelect: "Keine Daten in den SQLite-Protokollen für den ausgewählten Bereich.",
    gRAPHICALPROJECTTIMEDISTRIBUTI: "GRAFISCHE PROJEKT-ZEITVERTEILUNG",
    pLAINSQLITELOGSDUMP: "EINFACHER SQLITE-PROTOKOLL-DUMP",
    copiedToClipboard: "In die Zwischenablage kopiert!",
    oxyFlowMinimizedToTrayEngineKe: "OxyFlow in die Taskleiste minimiert. Der Motor läuft weiter.",
    "gUIClosedOxyFlowEngineLogsUISh": "GUI geschlossen. Der OxyFlow-Motor protokolliert das Herunterfahren der UI und läuft weiter.",
    mITLicenseCreditsOxyFlow: "MIT-Lizenz & Credits (OxyFlow)",
    aboutFlowCreditsMIT: "Über Flow, Credits & MIT",
    aBOUTCREATORVIBECODINGVIBE: "ÜBER DEN SCHÖPFER & VIBE CODING",
    cOMPONENTCREATORSACKNOWLEDGEME: "DANKSAGUNGEN AN DIE KOMPONENTEN-ERSTELLER",
    forGorgeousConsistentVectorIco: "Für wunderschöne konsistente Vektor-Icons.",
    forCinematicReactiveStateTrans: "Für filmische reaktive Zustandsübergänge.",
    forRapidElegantResponsiveUtili: "Für schnelles, elegantes, responsives Utility-Styling.",
    forImmediateDevIterationsAndSo: "Für sofortige Dev-Iterationen und soliden reaktiven Zustand.",
    mITLICENSE: "MIT-LIZENZ",
    greatClose: "Großartig, schließen",
    noPatches: "Keine Patches",
    addLogManually: "Protokoll manuell hinzufügen (INSERT SQL)",
    selectTask: "-- Aufgabe auswählen --",
    noNote: "Keine Notiz",
    addLeave: "+ Urlaub hinzufügen (SQL INSERT)",
    addManualPatch: "Manuellen Patch hinzufügen",
    noPatchesOperatingStandard: "Keine Patches (patch_logs). Der Motor arbeitet im Standardmodus.",
    selectProject: "Projekt auswählen",
    noProjects: "Keine Projekte.",
    noTasksInProfile: "Keine Aufgaben in diesem Profil.",
    warningResetApp: "WARNUNG: Sind Sie sicher, dass Sie ALLE Protokolle, Aufgaben und Projekte löschen wollen? Feiertage werden nicht gelöscht. Diese Aktion kann nicht rückgängig gemacht werden! Geben Sie 'reset' ein, um zu bestätigen:",
    noActiveTimersThisMoment: "Momentan keine aktiven Timer.",
    cliStatusDesc: "Zeigt Details des aktiven laufenden Timers an",
    cliCompleteDesc: "Schaltet den Abschlussstatus einer Aufgabe um",
    cliLogsDesc: "Zeigt die Protokollhistorie aus sqlite time_logs",
    cliHolidaysDesc: "Listet Feiertage/Urlaube auf (Feiertag/Urlaub hinzufügen 2026-06-15 \"urlaub\" - speichert)",
    cliReportDesc: "Generiert Standard- und grafische Berichte für einen bestimmten Zeitraum",
    cliClearDesc: "Löscht den Konsolenbildschirm",
    cliErrNoProjects: "Keine Projekte in SQLite gefunden. Verwenden Sie: addproject \"Name\"",
    cliProjHeader: "│  ID  │ PROJEKTNAME                    │ ABGELAUFENE ZEIT (H:M:S) │",
    cliRequiresProjId: "Fehler: Sie müssen eine Projekt-ID angeben. Beispiel: tasks 1",
    cliProjNotExist: "Fehler: Projekt mit der ID existiert nicht.",
    cliProjNoTasksYet: "Projekt hat noch keine Aufgaben.",
    cliProjTasksHeader: "Aufgaben für Projekt",
    cliErrSpecifyProjQuotes: "Fehler: Geben Sie den Projektnamen in Anführungszeichen an. Beispiel: addproject \"Zouk-Projekt\"",
    cliSuccessCreatedProj: "Erfolg: Projekt in SQLite erstellt.",
    cliErrUsageAddTask: "Fehler: Verwendung: addtask <proj_id> \"<name>\".",
    cliSuccessAddedTask: "Erfolg: Aufgabe hinzugefügt",
    cliErrUsageAddSubtask: "Fehler: Verwendung: addsubtask <parent_task_id> \"<name>\".",
    cliSuccessAddedSubtask: "Erfolg: Unteraufgabe hinzugefügt",
    cliErrTaskNotExist: "Fehler: Aufgabe existiert nicht.",
    cliErrTaskCompleted: "Fehler: Aufgabe ist erledigt.",
    cliTimerStarted: "Timer gestartet für Aufgabe",
    cliNoActiveTimer: "Info: Derzeit läuft kein aktiver Timer.",
    cliTimerStopped: "Timer gestoppt für Aufgabe",
    cliStatusHeader: "================ AKTIVER TİMER STATUS ================",
    cliStateIdle: "Status: Leerlauf. Kein aktiver Tracker läuft.",
    cliUsageCompleteTask: "Fehler: Verwendung: complete <task_id>",
    cliTaskToggled: "Aufgabe erfolgreich umgeschaltet.",
    cliNoLogsFound: "SQLite Datenbank: Keine protokollierten Zeitsitzungen gefunden.",
    cliLogsHeader: "│ ID   │ PRJ ID │ GESTARTET UM │ STATUS   │ DAUER                  │",
    cliInvalidDateFormat: "Fehler: Ungültiges Datumsformat. Muss JJJJ-MM-TT sein.",
    cliNoHolidays: "SQLite Datenbank: Feiertags- und Urlaubstabelle ist leer.",
    cliHolidaysHeader: "│  ID  │ DATUM      │ TYP         │ NAME (FEIERTAG / URLAUB)       │",
    cliNoLogsPeriod: "Info: Keine Protokolleinträge gefunden für den Zeitraum",
    cliReportTimeHeader: "ZEITDAUERBERICHT",
    cliReportSysList: "--- EINFACHE LISTE DER SQLITE-PROTOKOLLE ---",
    cliReportGraph: "--- GRAFISCHE DARSTELLUNG DER AKTIVEN PROJEKTE (ASCII) ---"
  },
  manual: {
    osSelected: "Ausgewählte Ziel-Betriebssystem-Kompilierung",
    title: "Kompilierungshandbuch, Verknüpfungen & Arch (Tauri OS Guides)",
    description: "Schritt-für-Schritt-Anleitung zur Erstellung von Produktions-Binärdateien und Überblick über Verknüpfungen und Daemons.",
    compilationTitle: "I. Erstellen des App-Installers (Tauri CLI Kompilierung)",
    step1: "Stellen Sie sicher, dass Node.js mit dem Paketmanager installiert ist",
    step2: "Installieren Sie Rust-Kompilierungswerkzeuge",
    step3: "Gehen Sie in den Stammordner (wo sich Ihre package.json befindet) und installieren Sie die Pakete:",
    step4: "Starten Sie den Produktions-Build. Tauri kompiliert das JS-Framework und dann die Rust-Binärdatei:",
    step5: "Installer fertig! Sie finden ihn in:",
    shortcutsTitle: "II. Tastenkombinationen & System Tray Daemon",
    shortcutsDesc: "OxyFlow basiert auf einem eingebetteten Tauri-Daemon, was bedeutet, dass die zugrunde liegende C++- und SQLite-Engine nicht stirbt, wenn Sie die Schnittstelle (über die X-Schaltfläche) schließen.",
    shortcutToggleInterface: "Schnittstelle umschalten (In Taskleiste minimieren)",
    shortcutGlobalReturn: "Schnelle globale Wiederherstellung (Globale Verknüpfung)",
    shortcutEmergencyStop: "Notstopp aller Timer",
    shortcutToggleTimer: "Aktuellen aktiven Timer starten / stoppen",
    shortcutSystemCli: "System-Ebene CLI"
  },
  credits: {
    description: "Lizenz, Nutzungsbedingungen und Biografie des Hauptentwicklers.",
    zoukBody: "Ich habe dieses System entwickelt, um als Zeitassistent zu fungieren, der anmutig eine versteckte CLI-Engine mit visuellen Zuständen für jemanden verschmilzt, der puren Fokus braucht. Gebaut für jemanden Wichtigen, inspiriert durch meine Leidenschaft für Tanz (Brasilianischer Zouk) und das Programmieren."
  },
  app: {
    guiClosedTitle: "OxyFlow GUI Geschlossen",
    guiClosedDesc: "Die Rust- & SQLite-Engine läuft weiterhin im Hintergrund (~8MB RAM).",
    restartGui: "GUI-Client neu starten",
    maximizeRestore: "OxyFlow UI maximiert.",
    stoppedThreads: "Alle aktiven Tracker-Threads wurden in SQLite ausgesetzt.",
    sizeChanged: "Schnittstellengröße geändert in:",
    sizeSmall: "Klein",
    sizeMedium: "Mittel",
    sizeLarge: "Groß",
    closeToTray: "In Taskleiste schließen",
    minimizeToTray: "In Taskleiste minimieren",
    fullScreen: "Vollbild",
    searchingPid: "suchen...",
    searchingEngine: "🔎 SUCHE ENGINE...",
    activeEngine: "✔️ AKTIV (SQLite)",
    subtitle: "Rust & SQLite microORM Engine • Hintergrundunterstützung für mehrere Projekte",
    themeDark: "Dunkel",
    themeLight: "Hell",
    themeHighContrast: "Kontrast",
    themeSystem: "Sys",
    noTaskSelected: "Wählen Sie zuerst eine Aufgabe aus, um den Timer zu starten / stoppen."
  }
};

const output = "export const de = " + JSON.stringify(de, null, 2) + ";\n";
fs.writeFileSync('src/utils/i18n/de.ts', output, 'utf8');
console.log('generated de.ts');
