var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var es_exports = {};
__export(es_exports, {
  es: () => es
});
module.exports = __toCommonJS(es_exports);
const es = {
  "common": {
    "cancel": "Cancelar",
    "save": "Guardar",
    "edit": "Editar",
    "delete": "Eliminar",
    "add": "A\xF1adir",
    "close": "Cerrar",
    "error": "Error",
    "success": "\xC9xito",
    "warning": "Advertencia",
    "yes": "S\xED",
    "no": "No",
    "confirm": "Confirmar"
  },
  "themes": {
    "lightDesc": "Light appearance",
    "darkDesc": "Dark appearance",
    "highContrastDesc": "High contrast UI",
    "systemDesc": "System defaults",
    "light": "Claro",
    "dark": "Oscuro",
    "highContrast": "Alto contraste",
    "system": "Sistema"
  },
  "tabs": {
    "reports": "Informes",
    "backup": "Copia de seguridad",
    "main": "Principal",
    "cli": "Consola CLI",
    "db": "Base de datos",
    "options": "Opciones",
    "manual": "Manual",
    "credits": "Cr\xE9ditos",
    "rust": "Rust Source"
  },
  "engine": {
    "configTitle": "Opciones del Motor y Daemons",
    "configDesc": "Configuraciones avanzadas del motor microORM OxyFlow.",
    "autoStart": "Iniciar al arrancar el sistema",
    "autoPauseOnSleep": "Pausar autom\xE1ticamente con la suspensi\xF3n",
    "minimizeToTrayDefault": "Minimizar a la bandeja al cerrar",
    "includePatchesInReports": "Incluir parches de tiempo en res\xFAmenes",
    "searching": "Buscando instancia activa del motor OxyFlow...",
    "connecting": "Conectando a la base de datos sqlite3 y analizando...",
    "connected": "Conectado al Daemon OxyFlow",
    "synced": "Motor sincronizado",
    "threads": "hilos de seguimiento (ejecuci\xF3n simult\xE1nea).",
    "minimizeToTray": "Minimizar a la bandeja",
    "sqlReset": "Restablecer base de datos (SQL Reset)"
  },
  "gui": {
    "newProject": "Nuevo Proyecto",
    "addTask": "Agregar Tarea",
    "addSubtask": "Agregar Subtarea",
    "projectName": "Nombre del Proyecto",
    "dashboardTitle": "Panel de Control",
    "tasksAndSubtasks": "Tareas y Subtareas",
    "projectTotalTime": "Tiempo Total del Proyecto",
    "activeTracker": "Rastreadores Activos",
    "stopAllThreads": "Suspender todo el rastreo",
    "selectProject": "Seleccionar proyecto",
    "noTasksInProject": "A\xFAn no hay tareas en este proyecto. \xA1Agrega algunas abajo!",
    "taskName": "Nombre de la Tarea",
    "addSubtaskTitle": "A\xF1adir Nueva Subtarea",
    "addNewProject": "A\xF1adir Nuevo Proyecto",
    "enterProjectName": "Ingresar nombre del proyecto",
    "chooseProjectColor": "Elegir color de acento",
    "enterMainTaskName": "Ingresar nombre de la tarea principal",
    "subtaskLabel": "Subtarea",
    "counterLabel": "Contador",
    "inProgressLabel": "En Curso",
    "holidaysAndLeaves": "Vacaciones y D\xEDas Libres",
    "addHolidayLeave": "A\xF1adir d\xEDa libre/vacaci\xF3n",
    "reportsTitle": "Registro de Informes",
    "periodReport": "Informe Peri\xF3dico",
    "createdAt": "Creado el",
    "color": "Color",
    "status": "Estado",
    "actions": "Acciones"
  },
  "settings": {
    "hardResetDesc": "Deleting all data...",
    "hardResetBtn": "Reset database",
    "title": "Interface & Application Settings",
    "description": "Manage global settings, language, colors, and API integrations.",
    "holidaysTitle": "Holidays & Regional Settings",
    "addLanguage": "A\xF1adir idioma",
    "customLanguageTitle": "Idioma personalizado",
    "customLanguageKey": "Clave",
    "keyLabel": "Clave",
    "valueLabel": "Valor",
    "saveCustomTranslation": "Guardar",
    "theme": "Tema de interfaz",
    "destructiveZone": "Zona destructiva",
    "engineConfig": "Configuraci\xF3n del motor",
    "systemTray": "Minimizar en la bandeja del sistema",
    "sendLogsToApi": "Enviar registros a una API",
    "apiUrl": "URL de API",
    "apiToken": "Token de API",
    "apiMethod": "M\xE9todo HTTP",
    "apiMethodTitle": "M\xE9todo para API",
    "apiMethodDesc": "Elija POST o PUT.",
    "apiHeaders": "Cabeceras personalizadas",
    "apiHeadersTitle": "Cabeceras",
    "apiHeadersDesc": "A\xF1adir JSON de cabeceras personalizadas"
  },
  "tests": {
    "testsTitle": "Panel de Pruebas Unitarias (Verificaci\xF3n del motor Rust)",
    "runMockTests": "Ejecutar pruebas de integraci\xF3n SQLite y Tauri"
  },
  "help": {
    "howToCompileTitle": "Compilaci\xF3n y Soporte",
    "helpAndDocumentation": "Centro de Ayuda y Documentaci\xF3n",
    "compileWizard": "Gu\xEDa paso a paso de compilaci\xF3n"
  },
  "dynamic": {
    "createdAtLabel": "Created At:",
    "archiveNoun": "Archive",
    "archive": "Archive",
    "unarchive": "Restore",
    "hideSqlitePreview": "Hide SQLite Database Preview",
    "exploreSqliteStructure": "Explore SQLite Table Structure (MicroORM)",
    "records": "records",
    "recordsPlural": "records",
    "andMoreRows": "...and {x} more rows",
    "actionsCrud": "actions (SQL CRUD)",
    "originalValue": "original",
    "dbTitle": "Tables Manager & History Audit (OxyFlow Backend)",
    "dbDesc": "View raw JSON/SQLite background database records. Thanks to timestamp logging, the calculator calculates time retrospectively, meaning you don't need to keep the application running. You can freely edit entries - their original values and change history are always preserved.",
    "tauriDriver": "Tauri SQLite Driver",
    "exportDb": "Export database",
    "entriesCrucialLabel": "Entries are crucial: time is calculated based on them. It works backward, you don't need to be logged in live.",
    "patchTableAllows": "The patch table allows patching sleep gaps or manually creating new periods to include in total work time.",
    "actionsLabel": "actions",
    "backupDesc": "Perform an immediate dump of the entire SQLite database, including project structures, logs, and patch fixes, or load a ready backup.",
    "webhookDesc": "Configure OxyFlow to send time dumps directly to an external system or database.",
    "apiAddress": "API Address",
    "bearerAuthTitle": "API Token (Bearer Auth)",
    "quickShortcuts": "Quick clickable shortcuts:",
    "settings_data": {
      "title": "Interface & Application Settings",
      "description": "Manage global settings, language, colors, and API integrations.",
      "holidaysTitle": "Holidays & Regional Settings"
    },
    "engine_data": {
      "configTitle": "Engine Options & Daemons",
      "configDesc": "Advanced OxyFlow microORM engine settings.",
      "autoStart": "Start on system boot",
      "autoPauseOnSleep": "Auto pause running timers on sleep",
      "minimizeToTrayDefault": "Minimize to tray on window close",
      "includePatchesInReports": "Include time patches in summaries"
    },
    "projects": "Proyectos",
    "nenhumProjetoAindaAdicioneUmAc": "A\xFAn sin proyectos.",
    "registradoHoje": "Registrado hoy",
    "todosOsRastreadoresParados": "Todos los rastreadores detenidos",
    "selecioneUmaTarefaAbaixoEJogue": "Selecciona una tarea para comenzar.",
    "idleSQLReady": "Inactivo (SQL listo)",
    "tasksFlow": "Tareas y Flujo",
    "holidaysLeaves": "Vacaciones",
    "summaryReports": "Informes",
    "total": "Total",
    "createAMainProjectTaskAboveThe": "Crea un proyecto arriba.",
    "enterSubtaskName": "Introduce el nombre de la subtarea...",
    "resourceDatabaseTable": "Tabla de base de datos",
    "holidaysVacations": "D\xEDas festivos y vacaciones",
    "rEGISTERNEWDAYOFFSQLINSERT": "REGISTRAR NUEVO D\xCDA LIBRE",
    "date": "Fecha",
    "type": "Tipo",
    "vacationLeave": "Vacaciones",
    "officialHoliday": "D\xEDa festivo",
    "descriptionCause": "Descripci\xF3n",
    "eGVibeDancingLeave": "P. ej., fiesta...",
    "save": "Guardar",
    "sQLiteHolidaysTableRowsMicroOR": "Tabla de d\xEDas festivos",
    "recordName": "Nombre",
    "scheduledDate": "Fecha planificada",
    "weekday": "D\xEDa",
    "actions": "Acciones",
    "noEntriesFoundInputAVacationAb": "No se encontraron entradas.",
    "hOLIDAY": "FESTIVO",
    "vACATION": "VACACIONES",
    "deleteSQLDELETE": "Eliminar",
    "sQLAnalyticsEngine": "Motor de an\xE1lisis SQL",
    "timeSummariesReports": "Res\xFAmenes",
    "tODAYTOTAL": "HOY",
    "sQLiteLogsSumForToday": "Suma de hoy",
    "wEEKTOTAL": "SEMANA",
    "fromMondayUntilNow": "De lunes a ahora",
    "mONTHTOTAL": "MES",
    "accumulatedMonthSeconds": "Segundos del mes acumulados",
    "period": "Per\xEDodo:",
    "today": "Hoy",
    "week": "Semana",
    "month": "Mes",
    "all": "Todo",
    "sortBy": "Ordenar por:",
    "durationHighestFirst": "Duraci\xF3n",
    "dateChronological": "Fecha",
    "noDataInSqliteLogsForTheSelect": "Sin datos.",
    "gRAPHICALPROJECTTIMEDISTRIBUTI": "DISTRIBUCI\xD3N GR\xC1FICA",
    "pLAINSQLITELOGSDUMP": "REGISTROS SQLITE",
    "copiedToClipboard": "\xA1Copiado al portapapeles!",
    "oxyFlowMinimizedToTrayEngineKe": "Minimizado a la bandeja.",
    "gUIClosedOxyFlowEngineLogsUISh": "GUI cerrada.",
    "mITLicenseCreditsOxyFlow": "Licencia MIT y Cr\xE9ditos",
    "aboutFlowCreditsMIT": "Acerca de Flow, Cr\xE9ditos y MIT",
    "aBOUTCREATORVIBECODINGVIBE": "SOBRE EL CREADOR",
    "cOMPONENTCREATORSACKNOWLEDGEME": "AGRADECIMIENTOS",
    "forGorgeousConsistentVectorIco": "Para \xEDconos hermosos.",
    "forCinematicReactiveStateTrans": "Para animaciones.",
    "forRapidElegantResponsiveUtili": "Para estilos.",
    "forImmediateDevIterationsAndSo": "Para desarrollo.",
    "mITLICENSE": "LICENCIA MIT",
    "greatClose": "Cerrar",
    "countingEngine": "Counting Engine v0.1",
    "createdForRhythm": "Creado para el ritmo",
    "heroDescription": "A\xF1ada tareas, expanda subtareas con microORM SQLite sin tener que hacer clic innecesariamente. Administre su tiempo de manera sencilla y con estilo.",
    "noPatches": "Sin parches",
    "addLogManually": "A\xF1adir registro manualmente",
    "selectTask": "-- Seleccionar tarea --",
    "noNote": "Sin nota",
    "addLeave": "+ A\xF1adir ausencia",
    "addManualPatch": "A\xF1adir parche manual",
    "noPatchesOperatingStandard": "Sin parches. Modo est\xE1ndar.",
    "selectProject": "Seleccionar proyecto",
    "noProjects": "Sin proyectos.",
    "noTasksInProfile": "No hay tareas en este perfil.",
    "warningResetApp": "ADVERTENCIA: \xBFDesea eliminar TODOS los registros, tareas y proyectos? Escriba 'reset' para confirmar:",
    "noActiveTimersThisMoment": "No hay temporizadores activos en este momento.",
    "cliStatusDesc": "Muestra detalles del temporizador activo",
    "cliCompleteDesc": "Alterna el estado completado de una tarea",
    "cliLogsDesc": "Muestra historial de logs de SQLite",
    "cliHolidaysDesc": "Muestra festivos/vacaciones",
    "cliReportDesc": "Genera informes visuales",
    "cliClearDesc": "Limpia la consola",
    "cliErrNoProjects": "No se encontraron proyectos.",
    "cliProjHeader": "\u2502  ID  \u2502 NOMBRE DEL PROYECTO            \u2502 TIEMPO INVERTIDO       \u2502",
    "cliRequiresProjId": "Error: Falt\xF3 ID de proyecto.",
    "cliProjNotExist": "Error: El proyecto no existe.",
    "cliProjNoTasksYet": "El proyecto no tiene tareas a\xFAn.",
    "cliProjTasksHeader": "Tareas para proyecto",
    "cliErrSpecifyProjQuotes": "Error: Nombre del proyecto entre comillas.",
    "cliSuccessCreatedProj": "\xC9xito: Proyecto creado.",
    "cliErrUsageAddTask": "Error: Uso addtask",
    "cliSuccessAddedTask": "\xC9xito: Tarea a\xF1adida",
    "cliErrUsageAddSubtask": "Error: Uso addsubtask",
    "cliSuccessAddedSubtask": "\xC9xito: Subtarea",
    "cliErrTaskNotExist": "Error: Tarea no existe.",
    "cliErrTaskCompleted": "Error: Tarea completada.",
    "cliTimerStarted": "Temporizador iniciado para",
    "cliNoActiveTimer": "Info: Ning\xFAn temporizador activo.",
    "cliTimerStopped": "Temporizador detenido para",
    "cliStatusHeader": "== ESTADO TEMPORIZADOR ==",
    "cliStateIdle": "Estado: Inactivo",
    "cliUsageCompleteTask": "Error",
    "cliTaskToggled": "Tarea alternada",
    "cliNoLogsFound": "No se encontraron logs",
    "cliLogsHeader": "\u2502  ID  \u2502 PRJ ID \u2502 INICIADO   \u2502 ESTADO   \u2502 DURACI\xD3N               \u2502",
    "cliInvalidDateFormat": "Formato incorrecto",
    "cliNoHolidays": "Sin vacaciones",
    "cliHolidaysHeader": "\u2502  ID  \u2502 FECHA      \u2502 TIPO        \u2502 NOMBRE                         \u2502",
    "cliNoLogsPeriod": "Sin registros para per\xEDodo",
    "cliReportTimeHeader": "INFORME",
    "cliReportSysList": "--- REGISTROS ---",
    "cliReportGraph": "--- GR\xC1FICO ---"
  },
  "manual": {
    "osSelected": "Compilaci\xF3n del SO seleccionada",
    "title": "Manual de Compilaci\xF3n, Atajos y Arq.",
    "description": "Gu\xEDa para compilar binarios y resumen de atajos y daemons.",
    "compilationTitle": "I. Compilar el Instalador (CLI Tauri)",
    "step1": "Aseg\xFArate de instalar Node.js y el gestor de paquetes",
    "step2": "Instala las herramientas de compilaci\xF3n de Rust",
    "step3": "Ingresa a la carpeta principal e instala los paquetes:",
    "step4": "Inicia el proceso de producci\xF3n. Tauri compilar\xE1 el JS y luego el binario Rust:",
    "step5": "\xA1Instalador listo! Lo encontrar\xE1s en:",
    "shortcutsTitle": "II. Atajos de teclado y Daemon",
    "shortcutsDesc": "OxyFlow se basa en un daemon Tauri, el motor C++ y SQLite seguir\xE1n funcionando.",
    "shortcutToggleInterface": "Alternar interfaz (Minimizar)",
    "shortcutGlobalReturn": "Restauraci\xF3n r\xE1pida global",
    "shortcutEmergencyStop": "Parada de emergencia",
    "shortcutToggleTimer": "Iniciar / Detener temporizador",
    "shortcutSystemCli": "CLI a nivel de sistema"
  },
  "credits": {
    "description": "Licencia, t\xE9rminos e informaci\xF3n del desarrollador.",
    "zoukBody": "Creado para funcionar como un asistente de tiempo sin interrupciones."
  },
  "app": {
    "guiClosedTitle": "Interfaz Cerrada",
    "guiClosedDesc": "El motor sigue ejecut\xE1ndose en segundo plano (~8MB).",
    "restartGui": "Reiniciar Cliente",
    "maximizeRestore": "Interfaz maximizada.",
    "stoppedThreads": "Seguimiento suspendido en SQLite.",
    "sizeChanged": "Tama\xF1o modificado a:",
    "sizeSmall": "Peque\xF1o",
    "sizeMedium": "Mediano",
    "sizeLarge": "Grande",
    "closeToTray": "Cerrar en la bandeja",
    "minimizeToTray": "Minimizar a la bandeja",
    "fullScreen": "Pantalla completa",
    "searchingPid": "buscando...",
    "searchingEngine": "\u{1F50D} BUSCANDO MOTOR...",
    "activeEngine": "\u2714\uFE0F ACTIVO (SQLite)",
    "subtitle": "Motor Rust y SQLite \u2022 Soporte para m\xFAltiples proyectos",
    "themeDark": "Oscuro",
    "themeLight": "Claro",
    "themeHighContrast": "Alto",
    "themeSystem": "Sis",
    "noTaskSelected": "Seleccione una tarea primero para iniciar."
  }
};
