var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var fr_exports = {};
__export(fr_exports, {
  fr: () => fr
});
module.exports = __toCommonJS(fr_exports);
const fr = {
  "common": {
    "cancel": "Annuler",
    "save": "Enregistrer",
    "edit": "Modifier",
    "delete": "Supprimer",
    "add": "Ajouter",
    "close": "Fermer",
    "error": "Erreur",
    "success": "Succ\xE8s",
    "warning": "Avertissement",
    "yes": "Oui",
    "no": "Non",
    "confirm": "Confirmer"
  },
  "themes": {
    "lightDesc": "Light appearance",
    "darkDesc": "Dark appearance",
    "highContrastDesc": "High contrast UI",
    "systemDesc": "System defaults",
    "light": "Clair",
    "dark": "Sombre",
    "highContrast": "Contraste \xE9lev\xE9",
    "system": "Syst\xE8me"
  },
  "tabs": {
    "reports": "Rapports",
    "backup": "Sauvegarde",
    "main": "Principal",
    "cli": "Console CLI",
    "db": "Base de donn\xE9es",
    "options": "Options",
    "manual": "Manuel",
    "credits": "Cr\xE9ditos",
    "rust": "Rust Source"
  },
  "engine": {
    "configTitle": "Options du Moteur & D\xE9mons",
    "configDesc": "Param\xE8tres avanc\xE9s du moteur microORM.",
    "autoStart": "D\xE9marrer avec le syst\xE8me",
    "autoPauseOnSleep": "Mettre en pause avec la mise en veille",
    "minimizeToTrayDefault": "Minimiser dans la barre en fermant",
    "includePatchesInReports": "Inclure les correctifs dans les r\xE9sum\xE9s",
    "searching": "Recherche de l'instance du moteur...",
    "connecting": "Connexion \xE0 sqlite3 et analyse...",
    "connected": "Connect\xE9 au D\xE9mon OxyFlow",
    "synced": "Moteur synchronis\xE9",
    "threads": "processus en parall\xE8le (projets en cours).",
    "minimizeToTray": "Minimiser dans la barre",
    "sqlReset": "R\xE9initialiser la base (SQL Reset)"
  },
  "gui": {
    "newProject": "Nouveau Projet",
    "addTask": "Ajouter une T\xE2che",
    "addSubtask": "Ajouter une Sous-t\xE2che",
    "projectName": "Nom du Projet",
    "dashboardTitle": "Tableau de Bord",
    "tasksAndSubtasks": "T\xE2ches & Sous-t\xE2ches",
    "projectTotalTime": "Temps Total du Projet",
    "activeTracker": "Traqueurs Actifs",
    "stopAllThreads": "Suspendre tout le suivi",
    "selectProject": "S\xE9lectionner un projet",
    "noTasksInProject": "Pas encore de t\xE2ches dans ce projet. Ajoutez-en ci-dessous !",
    "taskName": "Nom de la t\xE2che",
    "addSubtaskTitle": "Ajouter une nouvelle sous-t\xE2che",
    "addNewProject": "Ajouter un nouveau projet",
    "enterProjectName": "Entrez le nom du projet",
    "chooseProjectColor": "Choisissez la couleur du projet",
    "enterMainTaskName": "Entrez le nom de la t\xE2che",
    "subtaskLabel": "Sous-t\xE2che",
    "counterLabel": "Compteur",
    "inProgressLabel": "En Cours",
    "holidaysAndLeaves": "Vacances & Cong\xE9s",
    "addHolidayLeave": "Ajouter un cong\xE9",
    "reportsTitle": "Journalisation des Rapports",
    "periodReport": "Rapport P\xE9riodique",
    "createdAt": "Cr\xE9\xE9 le",
    "color": "Couleur",
    "status": "Statut",
    "actions": "Actions"
  },
  "settings": {
    "hardResetDesc": "Deleting all data...",
    "hardResetBtn": "Reset database",
    "title": "Interface & Application Settings",
    "description": "Manage global settings, language, colors, and API integrations.",
    "holidaysTitle": "Holidays & Regional Settings",
    "addLanguage": "Ajouter une langue",
    "customLanguageTitle": "Langue personnalis\xE9e",
    "customLanguageKey": "Cl\xE9",
    "keyLabel": "Cl\xE9",
    "valueLabel": "Valeur",
    "saveCustomTranslation": "Enregistrer",
    "theme": "Th\xE8me de l'interface",
    "destructiveZone": "Zone destructrice",
    "engineConfig": "Configuration du moteur",
    "systemTray": "R\xE9duire dans la zone de notification",
    "sendLogsToApi": "Envoyer les journaux \xE0 l'API",
    "apiUrl": "URL de l'API",
    "apiToken": "Jeton de l'API",
    "apiMethod": "M\xE9thode HTTP",
    "apiMethodTitle": "M\xE9thode d'action API",
    "apiMethodDesc": "Choisissez POST ou PUT.",
    "apiHeaders": "En-t\xEAtes",
    "apiHeadersTitle": "T\xEAtes personnalis\xE9es",
    "apiHeadersDesc": "Ajoutez du JSON pour l'en-t\xEAte API"
  },
  "tests": {
    "testsTitle": "Panneau de Tests Unitaires",
    "runMockTests": "Ex\xE9cuter les tests d'int\xE9gration"
  },
  "help": {
    "howToCompileTitle": "Compilation & Support",
    "helpAndDocumentation": "Centre d'Aide & Docs",
    "compileWizard": "Guide de compilation \xE9tape par \xE9tape"
  },
  "dynamic": {
    "createdAtLabel": "Created At:",
    "archiveNoun": "Archive",
    "archive": "Archive",
    "unarchive": "Restore",
    "hideSqlitePreview": "Hide SQLite Database Preview",
    "exploreSqliteStructure": "Explore SQLite Table Structure (MicroORM)",
    "records": "records",
    "recordsPlural": "records",
    "andMoreRows": "...and {x} more rows",
    "actionsCrud": "actions (SQL CRUD)",
    "originalValue": "original",
    "dbTitle": "Tables Manager & History Audit (OxyFlow Backend)",
    "dbDesc": "View raw JSON/SQLite background database records. Thanks to timestamp logging, the calculator calculates time retrospectively, meaning you don't need to keep the application running. You can freely edit entries - their original values and change history are always preserved.",
    "tauriDriver": "Tauri SQLite Driver",
    "exportDb": "Export database",
    "entriesCrucialLabel": "Entries are crucial: time is calculated based on them. It works backward, you don't need to be logged in live.",
    "patchTableAllows": "The patch table allows patching sleep gaps or manually creating new periods to include in total work time.",
    "actionsLabel": "actions",
    "backupDesc": "Perform an immediate dump of the entire SQLite database, including project structures, logs, and patch fixes, or load a ready backup.",
    "webhookDesc": "Configure OxyFlow to send time dumps directly to an external system or database.",
    "apiAddress": "API Address",
    "bearerAuthTitle": "API Token (Bearer Auth)",
    "quickShortcuts": "Quick clickable shortcuts:",
    "settings_data": {
      "title": "Interface & Application Settings",
      "description": "Manage global settings, language, colors, and API integrations.",
      "holidaysTitle": "Holidays & Regional Settings"
    },
    "engine_data": {
      "configTitle": "Engine Options & Daemons",
      "configDesc": "Advanced OxyFlow microORM engine settings.",
      "autoStart": "Start on system boot",
      "autoPauseOnSleep": "Auto pause running timers on sleep",
      "minimizeToTrayDefault": "Minimize to tray on window close",
      "includePatchesInReports": "Include time patches in summaries"
    },
    "projects": "Projets",
    "nenhumProjetoAindaAdicioneUmAc": "Pas de projets.",
    "registradoHoje": "Enregistr\xE9 aujourd'hui",
    "todosOsRastreadoresParados": "Tous les traceurs arr\xEAt\xE9s",
    "selecioneUmaTarefaAbaixoEJogue": "S\xE9lectionnez une t\xE2che pour d\xE9marrer.",
    "idleSQLReady": "Inactif (SQL pr\xEAt)",
    "tasksFlow": "T\xE2ches & Flux",
    "holidaysLeaves": "Cong\xE9s",
    "summaryReports": "Rapports",
    "total": "Total",
    "createAMainProjectTaskAboveThe": "Cr\xE9ez un projet au-dessus.",
    "enterSubtaskName": "Entrez le nom de la sous-t\xE2che...",
    "resourceDatabaseTable": "Table de la base de donn\xE9es",
    "holidaysVacations": "Jours f\xE9ri\xE9s & Vacances",
    "rEGISTERNEWDAYOFFSQLINSERT": "ENREGISTRER UN NOUVEAU JOUR DE CONG\xC9",
    "date": "Date",
    "type": "Type",
    "vacationLeave": "Vacances",
    "officialHoliday": "Jour f\xE9ri\xE9",
    "descriptionCause": "Description",
    "eGVibeDancingLeave": "Ex. vacances...",
    "save": "Enregistrer",
    "sQLiteHolidaysTableRowsMicroOR": "Table des cong\xE9s",
    "recordName": "Nom",
    "scheduledDate": "Date pr\xE9vue",
    "weekday": "Jour",
    "actions": "Actions",
    "noEntriesFoundInputAVacationAb": "Aucune entr\xE9e.",
    "hOLIDAY": "JOUR F\xC9RI\xC9",
    "vACATION": "VACACIONES",
    "deleteSQLDELETE": "Supprimer",
    "sQLAnalyticsEngine": "Moteur d'analyse SQL",
    "timeSummariesReports": "R\xE9sum\xE9s",
    "tODAYTOTAL": "AUJOURD'HUI",
    "sQLiteLogsSumForToday": "Total d'aujourd'hui",
    "wEEKTOTAL": "SEMAINE",
    "fromMondayUntilNow": "De lundi \xE0 maintenant",
    "mONTHTOTAL": "MOIS",
    "accumulatedMonthSeconds": "Secondes accumul\xE9es ce mois",
    "period": "P\xE9riode :",
    "today": "Aujourd'hui",
    "week": "Semaine",
    "month": "Mois",
    "all": "Tout",
    "sortBy": "Trier par :",
    "durationHighestFirst": "Dur\xE9e",
    "dateChronological": "Date",
    "noDataInSqliteLogsForTheSelect": "Pas de donn\xE9es.",
    "gRAPHICALPROJECTTIMEDISTRIBUTI": "DISTRIBUTION GRAPHIQUE",
    "pLAINSQLITELOGSDUMP": "JOURNAUX SQLITE",
    "copiedToClipboard": "Copi\xE9 !",
    "oxyFlowMinimizedToTrayEngineKe": "R\xE9duit dans la zone de notification.",
    "gUIClosedOxyFlowEngineLogsUISh": "Interface GUI ferm\xE9e.",
    "mITLicenseCreditsOxyFlow": "Licence MIT & Cr\xE9ditos",
    "aboutFlowCreditsMIT": "A propos de Flow, cr\xE9dits & MIT",
    "aBOUTCREATORVIBECODINGVIBE": "\xC0 PROPOS DU CR\xC9ATEUR",
    "cOMPONENTCREATORSACKNOWLEDGEME": "REMERCIEMENTS",
    "forGorgeousConsistentVectorIco": "Pour de superbes ic\xF4nes.",
    "forCinematicReactiveStateTrans": "Pour de belles animations.",
    "forRapidElegantResponsiveUtili": "Pour le style.",
    "forImmediateDevIterationsAndSo": "Pour le d\xE9veloppement.",
    "mITLICENSE": "LICENCE MIT",
    "greatClose": "Fermer",
    "countingEngine": "Counting Engine v0.1",
    "createdForRhythm": "Cr\xE9\xE9 pour le rythme",
    "heroDescription": "Ajoutez des t\xE2ches, d\xE9veloppez des sous-t\xE2ches avec microORM SQLite sans clics inutiles. G\xE9rez votre temps simplement et avec style.",
    "noPatches": "Aucun patch",
    "addLogManually": "Ajouter le journal manuellement",
    "selectTask": "-- S\xE9lectionner une t\xE2che --",
    "noNote": "Aucune note",
    "addLeave": "+ Ajouter un cong\xE9",
    "addManualPatch": "Ajouter un patch manuel",
    "noPatchesOperatingStandard": "Aucun patch. Mode standard.",
    "selectProject": "S\xE9lectionner un projet",
    "noProjects": "Aucun projet.",
    "noTasksInProfile": "Aucune t\xE2che dans ce profil.",
    "warningResetApp": "ATTENTION : Voulez-vous supprimer TOUS les journaux, t\xE2ches et projets ? Tapez 'reset' pour confirmer :",
    "noActiveTimersThisMoment": "Aucun minuteur actif pour le moment.",
    "cliStatusDesc": "Affiche les d\xE9tails du chronom\xE8tre actif",
    "cliCompleteDesc": "Basculer l'\xE9tat termin\xE9 d'une t\xE2che",
    "cliLogsDesc": "Affiche l'historique des journaux SQLite",
    "cliHolidaysDesc": "Affiche les jours f\xE9ri\xE9s/cong\xE9s",
    "cliReportDesc": "G\xE9n\xE8re des rapports visuels",
    "cliClearDesc": "Effacer la console",
    "cliErrNoProjects": "Aucun projet trouv\xE9.",
    "cliProjHeader": "\u2502  ID  \u2502 NOM DU PROJET                  \u2502 TEMPS \xC9COUL\xC9            \u2502",
    "cliRequiresProjId": "Erreur: ID de projet manquant.",
    "cliProjNotExist": "Erreur: Le projet n'existe pas.",
    "cliProjNoTasksYet": "Le projet n'a pas encore de t\xE2ches.",
    "cliProjTasksHeader": "T\xE2ches pour le projet",
    "cliErrSpecifyProjQuotes": "Erreur: Nom de projet entre guillemets.",
    "cliSuccessCreatedProj": "Succ\xE8s : Projet cr\xE9\xE9.",
    "cliErrUsageAddTask": "Erreur : Utilisation addtask",
    "cliSuccessAddedTask": "Succ\xE8s : T\xE2che ajout\xE9e",
    "cliErrUsageAddSubtask": "Erreur : Utilisation addsubtask",
    "cliSuccessAddedSubtask": "Succ\xE8s : Sous-t\xE2che",
    "cliErrTaskNotExist": "Erreur: T\xE2che inexistante.",
    "cliErrTaskCompleted": "Erreur: T\xE2che termin\xE9e.",
    "cliTimerStarted": "Le chronom\xE8tre a commenc\xE9 pour",
    "cliNoActiveTimer": "Info : Aucun minuteur actif.",
    "cliTimerStopped": "Minuteur arr\xEAt\xE9 pour",
    "cliStatusHeader": "== \xC9TAT MINUTEUR ==",
    "cliStateIdle": "\xC9tat: Inactif",
    "cliUsageCompleteTask": "Erreur",
    "cliTaskToggled": "T\xE2che bascul\xE9e",
    "cliNoLogsFound": "Aucun log",
    "cliLogsHeader": "\u2502  ID  \u2502 PRJ ID \u2502 D\xC9MARR\xC9    \u2502 \xC9TAT     \u2502 DUR\xC9E                  \u2502",
    "cliInvalidDateFormat": "Format invalide",
    "cliNoHolidays": "Aucun cong\xE9",
    "cliHolidaysHeader": "\u2502  ID  \u2502 DATE       \u2502 TYPE        \u2502 NOM                            \u2502",
    "cliNoLogsPeriod": "Aucun \xE9l\xE9ment pour l'\xE9poque",
    "cliReportTimeHeader": "RAPPORT",
    "cliReportSysList": "--- LISTE DES JOURNAUX ---",
    "cliReportGraph": "--- GRAPHIQUE ---"
  },
  "manual": {
    "osSelected": "OS de compilation s\xE9lectionn\xE9",
    "title": "Manuel de Compilation et Raccourcis",
    "description": "Guide pour compiler les binaires et raccourcis du d\xE9mon.",
    "compilationTitle": "I. Construire l'Installateur (Tauri CLI)",
    "step1": "Assurez-vous d'installer Node.js",
    "step2": "Installez les outils de compilation Rust",
    "step3": "Allez dans le r\xE9pertoire racine et installez les paquets :",
    "step4": "D\xE9marrez la compilation. Tauri compilera le framework JS et le binaire :",
    "step5": "Installateur pr\xEAt ! Vous le trouverez :",
    "shortcutsTitle": "II. Raccourcis et D\xE9mon Serveur",
    "shortcutsDesc": "OxyFlow utilise un d\xE9mon, donc le moteur SQLite ne s'arr\xEAte pas avec l'interface.",
    "shortcutToggleInterface": "Basculer l'interface (Minimiser)",
    "shortcutGlobalReturn": "Restauration rapide globale",
    "shortcutEmergencyStop": "Arr\xEAt d'urgence des chronom\xE8tres",
    "shortcutToggleTimer": "D\xE9marrer / Arr\xEAter",
    "shortcutSystemCli": "CLI Syst\xE8me"
  },
  "credits": {
    "description": "Licence, termes et biographie du d\xE9veloppeur.",
    "zoukBody": "Syst\xE8me cr\xE9\xE9 pour \xEAtre un assistant en arri\xE8re-plan sans perturber le flux."
  },
  "app": {
    "guiClosedTitle": "Interface Ferm\xE9e",
    "guiClosedDesc": "Le moteur continue de fonctionner en arri\xE8re-plan (~8Mo RAM).",
    "restartGui": "Red\xE9marrer le Client",
    "maximizeRestore": "Interface maximis\xE9e.",
    "stoppedThreads": "Les suivis ont \xE9t\xE9 suspendus.",
    "sizeChanged": "Taille de l'interface modifi\xE9e :",
    "sizeSmall": "Petit",
    "sizeMedium": "Moyen",
    "sizeLarge": "Grand",
    "closeToTray": "Fermer dans la barre",
    "minimizeToTray": "Minimiser dans la barre",
    "fullScreen": "Plein \xE9cran",
    "searchingPid": "recherche...",
    "searchingEngine": "\u{1F50D} RECHERCHE DU MOTEUR...",
    "activeEngine": "\u2714\uFE0F ACTIF (SQLite)",
    "subtitle": "Moteur Rust & SQLite \u2022 Support de multiples projets",
    "themeDark": "Sombre",
    "themeLight": "Clair",
    "themeHighContrast": "Contraste",
    "themeSystem": "Sys",
    "noTaskSelected": "Veuillez s\xE9lectionner une t\xE2che pour d\xE9marrer."
  }
};
