var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var pt_br_exports = {};
__export(pt_br_exports, {
  ptBr: () => ptBr
});
module.exports = __toCommonJS(pt_br_exports);
const ptBr = {
  "common": {
    "cancel": "Cancelar",
    "save": "Salvar",
    "edit": "Editar",
    "delete": "Deletar",
    "add": "Adicionar",
    "close": "Fechar",
    "error": "Erro",
    "success": "Sucesso",
    "warning": "Aviso",
    "yes": "Sim",
    "no": "N\xE3o",
    "confirm": "Confirmar"
  },
  "themes": {
    "lightDesc": "Light appearance",
    "darkDesc": "Dark appearance",
    "highContrastDesc": "High contrast UI",
    "systemDesc": "System defaults",
    "light": "Claro",
    "dark": "Escuro",
    "highContrast": "Alto Contraste",
    "system": "Sistema"
  },
  "tabs": {
    "reports": "Relat\xF3rios",
    "backup": "Backup",
    "main": "Principal",
    "cli": "Console CLI",
    "db": "Banco de Dados",
    "options": "Op\xE7\xF5es",
    "manual": "Manual",
    "credits": "Cr\xE9ditos",
    "rust": "Rust Source"
  },
  "engine": {
    "configTitle": "Op\xE7\xF5es do Motor e Daemons",
    "configDesc": "Configura\xE7\xF5es avan\xE7adas do motor microORM.",
    "autoStart": "Iniciar ao iniciar o sistema",
    "autoPauseOnSleep": "Pausar rastreadores na suspens\xE3o",
    "minimizeToTrayDefault": "Minimizar para a bandeja ao fechar",
    "includePatchesInReports": "Incluir corre\xE7\xF5es de tempo nos relat\xF3rios",
    "searching": "Procurando inst\xE2ncia ativa do motor...",
    "connecting": "Conectando ao banco sqlite3 e analisando...",
    "connected": "Conectado ao Daemon OxyFlow",
    "synced": "Motor sincronizado",
    "threads": "processos de rastreamento (projetos simult\xE2neos).",
    "minimizeToTray": "Minimizar para a bandeja",
    "sqlReset": "Redefinir Banco de Dados (SQL Reset)"
  },
  "gui": {
    "newProject": "Novo Projeto",
    "addTask": "Adicionar Tarefa",
    "addSubtask": "Adicionar Subtarefa",
    "projectName": "Nome do Projeto",
    "dashboardTitle": "Painel de Controle",
    "tasksAndSubtasks": "Tarefas & Subtarefas",
    "projectTotalTime": "Tempo Total do Projeto",
    "activeTracker": "Rastreadores Ativos",
    "stopAllThreads": "Suspender todo o rastreamento",
    "selectProject": "Selecionar projeto",
    "noTasksInProject": "Ainda n\xE3o h\xE1 tarefas neste projeto. Adicione-as abaixo!",
    "taskName": "Nome da Tarefa",
    "addSubtaskTitle": "Adicionar Nova Subtarefa",
    "addNewProject": "Adicionar Novo Projeto",
    "enterProjectName": "Digite o nome do projeto",
    "chooseProjectColor": "Escolha a cor do projeto",
    "enterMainTaskName": "Digite o nome da tarefa principal",
    "subtaskLabel": "Subtarefa",
    "counterLabel": "Contador",
    "inProgressLabel": "Em Progresso",
    "holidaysAndLeaves": "Feriados & F\xE9rias",
    "addHolidayLeave": "Adicionar folga/f\xE9rias",
    "reportsTitle": "Registro de Relat\xF3rios",
    "periodReport": "Relat\xF3rio Peri\xF3dico",
    "createdAt": "Criado em",
    "color": "Cor",
    "status": "Status",
    "actions": "A\xE7\xF5es"
  },
  "settings": {
    "hardResetDesc": "Deleting all data...",
    "hardResetBtn": "Reset database",
    "title": "Interface & Application Settings",
    "description": "Manage global settings, language, colors, and API integrations.",
    "holidaysTitle": "Holidays & Regional Settings",
    "addLanguage": "Adicionar Idioma",
    "customLanguageTitle": "Idioma Personalizado",
    "customLanguageKey": "Chave",
    "keyLabel": "Chave",
    "valueLabel": "Valor",
    "saveCustomTranslation": "Salvar",
    "theme": "Tema da Interface",
    "destructiveZone": "Zona Destrutiva",
    "engineConfig": "Configura\xE7\xE3o do Motor",
    "systemTray": "Minimizar para a bandeja do sistema",
    "sendLogsToApi": "Enviar logs para API externa",
    "apiUrl": "URL da API",
    "apiToken": "Token da API",
    "apiMethod": "M\xE9todo HTTP",
    "apiMethodTitle": "M\xE9todo de envio da API",
    "apiMethodDesc": "Marque para PUT, desmarque para POST.",
    "apiHeaders": "Cabe\xE7alhos",
    "apiHeadersTitle": "Cabe\xE7alhos personalizados",
    "apiHeadersDesc": "JSON Headers"
  },
  "tests": {
    "testsTitle": "Painel de Testes Unit\xE1rios",
    "runMockTests": "Rodar testes de integra\xE7\xE3o SQLite & Tauri"
  },
  "help": {
    "howToCompileTitle": "Compila\xE7\xE3o & Suporte",
    "helpAndDocumentation": "Central de Ajuda e Documentos",
    "compileWizard": "Guia de compila\xE7\xE3o passo a passo"
  },
  "dynamic": {
    "createdAtLabel": "Created At:",
    "archiveNoun": "Archive",
    "archive": "Archive",
    "unarchive": "Restore",
    "hideSqlitePreview": "Hide SQLite Database Preview",
    "exploreSqliteStructure": "Explore SQLite Table Structure (MicroORM)",
    "records": "records",
    "recordsPlural": "records",
    "andMoreRows": "...and {x} more rows",
    "actionsCrud": "actions (SQL CRUD)",
    "originalValue": "original",
    "dbTitle": "Tables Manager & History Audit (OxyFlow Backend)",
    "dbDesc": "View raw JSON/SQLite background database records. Thanks to timestamp logging, the calculator calculates time retrospectively, meaning you don't need to keep the application running. You can freely edit entries - their original values and change history are always preserved.",
    "tauriDriver": "Tauri SQLite Driver",
    "exportDb": "Export database",
    "entriesCrucialLabel": "Entries are crucial: time is calculated based on them. It works backward, you don't need to be logged in live.",
    "patchTableAllows": "The patch table allows patching sleep gaps or manually creating new periods to include in total work time.",
    "actionsLabel": "actions",
    "backupDesc": "Perform an immediate dump of the entire SQLite database, including project structures, logs, and patch fixes, or load a ready backup.",
    "webhookDesc": "Configure OxyFlow to send time dumps directly to an external system or database.",
    "apiAddress": "API Address",
    "bearerAuthTitle": "API Token (Bearer Auth)",
    "quickShortcuts": "Quick clickable shortcuts:",
    "settings_data": {
      "title": "Interface & Application Settings",
      "description": "Manage global settings, language, colors, and API integrations.",
      "holidaysTitle": "Holidays & Regional Settings"
    },
    "engine_data": {
      "configTitle": "Engine Options & Daemons",
      "configDesc": "Advanced OxyFlow microORM engine settings.",
      "autoStart": "Start on system boot",
      "autoPauseOnSleep": "Auto pause running timers on sleep",
      "minimizeToTrayDefault": "Minimize to tray on window close",
      "includePatchesInReports": "Include time patches in summaries"
    },
    "projects": "Projetos",
    "nenhumProjetoAindaAdicioneUmAc": "Nenhum projeto ainda.",
    "registradoHoje": "Registrado hoje",
    "todosOsRastreadoresParados": "Todos os rastreadores parados",
    "selecioneUmaTarefaAbaixoEJogue": "Selecione uma tarefa para come\xE7ar.",
    "idleSQLReady": "Inativo (SQL Pronto)",
    "tasksFlow": "Tarefas e Fluxo",
    "holidaysLeaves": "F\xE9rias",
    "summaryReports": "Relat\xF3rios",
    "total": "Total",
    "createAMainProjectTaskAboveThe": "Crie um projeto acima.",
    "enterSubtaskName": "Digite o nome da subtarefa...",
    "resourceDatabaseTable": "Tabela do banco de dados",
    "holidaysVacations": "Feriados e F\xE9rias",
    "rEGISTERNEWDAYOFFSQLINSERT": "REGISTRAR NOVO DIA DE FOLGA",
    "date": "Data",
    "type": "Tipo",
    "vacationLeave": "F\xE9rias",
    "officialHoliday": "Feriado",
    "descriptionCause": "Descri\xE7\xE3o",
    "eGVibeDancingLeave": "Ex: Festa...",
    "save": "Salvar",
    "sQLiteHolidaysTableRowsMicroOR": "Tabela de feriados",
    "recordName": "Nome",
    "scheduledDate": "Data agendada",
    "weekday": "Dia da semana",
    "actions": "A\xE7\xF5es",
    "noEntriesFoundInputAVacationAb": "Nenhuma entrada encontrada.",
    "hOLIDAY": "FERIADO",
    "vACATION": "F\xC9RIAS",
    "deleteSQLDELETE": "Deletar",
    "sQLAnalyticsEngine": "Motor de an\xE1lise SQL",
    "timeSummariesReports": "Resumos",
    "tODAYTOTAL": "HOJE",
    "sQLiteLogsSumForToday": "Soma de hoje",
    "wEEKTOTAL": "SEMANA",
    "fromMondayUntilNow": "De segunda at\xE9 agora",
    "mONTHTOTAL": "M\xCAS",
    "accumulatedMonthSeconds": "Segundos do m\xEAs acumulados",
    "period": "Per\xEDodo:",
    "today": "Hoje",
    "week": "Semana",
    "month": "M\xEAs",
    "all": "Tudo",
    "sortBy": "Ordenar por:",
    "durationHighestFirst": "Dura\xE7\xE3o",
    "dateChronological": "Data",
    "noDataInSqliteLogsForTheSelect": "Sem dados.",
    "gRAPHICALPROJECTTIMEDISTRIBUTI": "DISTRIBUI\xC7\xC3O GR\xC1FICA",
    "pLAINSQLITELOGSDUMP": "LOGS DO SQLITE",
    "copiedToClipboard": "Copiado para a \xE1rea de transfer\xEAncia!",
    "oxyFlowMinimizedToTrayEngineKe": "Minimizado.",
    "gUIClosedOxyFlowEngineLogsUISh": "GUI fechada.",
    "mITLicenseCreditsOxyFlow": "Licen\xE7a MIT e Cr\xE9ditos",
    "aboutFlowCreditsMIT": "Sobre o Flow, Cr\xE9ditos e MIT",
    "aBOUTCREATORVIBECODINGVIBE": "SOBRE O CRIADOR",
    "cOMPONENTCREATORSACKNOWLEDGEME": "AGRADECIMENTOS",
    "forGorgeousConsistentVectorIco": "Para \xEDcones lindos.",
    "forCinematicReactiveStateTrans": "Para anima\xE7\xF5es.",
    "forRapidElegantResponsiveUtili": "Para estilos.",
    "forImmediateDevIterationsAndSo": "Para desenvolvimento.",
    "mITLICENSE": "LICEN\xC7A MIT",
    "greatClose": "Fechar",
    "countingEngine": "Counting Engine v0.1",
    "createdForRhythm": "Criado para o ritmo",
    "heroDescription": "Adicione tarefas, expanda subtarefas com microORM SQLite sem cliques desnecess\xE1rios. Gerencie seu tempo de forma simples e com estilo.",
    "noPatches": "Sem patches",
    "addLogManually": "Adicionar Log Manualmente",
    "selectTask": "-- Selecionar tarefa --",
    "noNote": "Sem nota",
    "addLeave": "+ Adicionar Folga",
    "addManualPatch": "Adicionar Patch Manual",
    "noPatchesOperatingStandard": "Sem patches. Modo padr\xE3o.",
    "selectProject": "Selecionar projeto",
    "noProjects": "Sem projetos.",
    "noTasksInProfile": "Sem tarefas neste perfil.",
    "warningResetApp": "AVISO: Deseja excluir TODOS os logs, tarefas e projetos? Digite 'reset' para confirmar:",
    "noActiveTimersThisMoment": "N\xE3o h\xE1 cron\xF4metros ativos no momento.",
    "cliStatusDesc": "Exibe detalhes do cron\xF4metro ativo",
    "cliCompleteDesc": "Alterna o status de conclus\xE3o de uma tarefa",
    "cliLogsDesc": "Mostra o hist\xF3rico de logs do SQLite",
    "cliHolidaysDesc": "Lista feriados/f\xE9rias",
    "cliReportDesc": "Gera relat\xF3rios visuais",
    "cliClearDesc": "Limpa o console",
    "cliErrNoProjects": "Nenhum projeto encontrado.",
    "cliProjHeader": "\u2502  ID  \u2502 NOME DO PROJETO                \u2502 TEMPO (H:M:S)          \u2502",
    "cliRequiresProjId": "Erro: Forne\xE7a o ID do projeto.",
    "cliProjNotExist": "Erro: O projeto n\xE3o existe.",
    "cliProjNoTasksYet": "O projeto ainda n\xE3o possui tarefas.",
    "cliProjTasksHeader": "Tarefas do projeto",
    "cliErrSpecifyProjQuotes": "Erro: Nome do projeto entre aspas.",
    "cliSuccessCreatedProj": "Acerto: Projeto criado.",
    "cliErrUsageAddTask": "Erro: Uso addtask",
    "cliSuccessAddedTask": "Acerto: Tarefa adicionada",
    "cliErrUsageAddSubtask": "Erro: Uso addsubtask",
    "cliSuccessAddedSubtask": "Acerto: Subtarefa",
    "cliErrTaskNotExist": "Erro: Tarefa n\xE3o existe.",
    "cliErrTaskCompleted": "Erro: A tarefa est\xE1 conclu\xEDda.",
    "cliTimerStarted": "Cron\xF4metro iniciado para",
    "cliNoActiveTimer": "Info: Nenhum cron\xF4metro ativo.",
    "cliTimerStopped": "Cron\xF4metro parado para",
    "cliStatusHeader": "== STATUS CRON\xD4METRO ==",
    "cliStateIdle": "Estado: Ausente",
    "cliUsageCompleteTask": "Erro",
    "cliTaskToggled": "Tarefa alternada",
    "cliNoLogsFound": "Sem logs",
    "cliLogsHeader": "\u2502 ID   \u2502 PRJ ID \u2502 INICIADO   \u2502 STATUS   \u2502 DURA\xC7\xC3O                \u2502",
    "cliInvalidDateFormat": "Formato inv\xE1lido",
    "cliNoHolidays": "Sem feriados",
    "cliHolidaysHeader": "\u2502  ID  \u2502 DATA       \u2502 TIPO        \u2502 NOME                           \u2502",
    "cliNoLogsPeriod": "Sem logs para per\xEDodo",
    "cliReportTimeHeader": "RELAT\xD3RIO DE TEMPO",
    "cliReportSysList": "--- LOGS ---",
    "cliReportGraph": "--- GR\xC1FICOS ---"
  },
  "manual": {
    "osSelected": "SO de compila\xE7\xE3o selecionado",
    "title": "Manual de Compila\xE7\xE3o e Atalhos",
    "description": "Guia para compilar os bin\xE1rios e resumo de atalhos e daemons.",
    "compilationTitle": "I. Compilar o Instalador (Tauri CLI)",
    "step1": "Certifique-se de instalar o Node.js e o gerenciador de pacotes",
    "step2": "Instale as ferramentas de compila\xE7\xE3o do Rust",
    "step3": "V\xE1 para a pasta raiz e instale os pacotes:",
    "step4": "Inicie a compila\xE7\xE3o. Tauri vai compilar o JS e o bin\xE1rio:",
    "step5": "Instalador pronto! Voc\xEA o encontrar\xE1 em:',",
    "shortcutsTitle": "II. Atalhos e Daemon na Bandeja do Sistema",
    "shortcutsDesc": "O OxyFlow \xE9 executado via daemon, o que significa que o SQLite n\xE3o morre quando a interface \xE9 fechada.",
    "shortcutToggleInterface": "Alternar interface (Minimizar)",
    "shortcutGlobalReturn": "Restaura\xE7\xE3o global r\xE1pida",
    "shortcutEmergencyStop": "Parada de emerg\xEAncia dos tempos",
    "shortcutToggleTimer": "Iniciar / Parar temporizador",
    "shortcutSystemCli": "CLI de Sistema"
  },
  "credits": {
    "description": "Licen\xE7a, termos de servi\xE7o e biografia.",
    "zoukBody": "Sistema constru\xEDdo para mesclar perfeitamente CLI em background e um estado visual responsivo."
  },
  "app": {
    "guiClosedTitle": "Interface Fechada",
    "guiClosedDesc": "O motor Rust & SQLite continua rodando no fundo (~8MB RAM).",
    "restartGui": "Reiniciar Cliente Visual",
    "maximizeRestore": "Interface maximizada.",
    "stoppedThreads": "O rastreamento foi suspenso no SQLite.",
    "sizeChanged": "Tamanho alterado para:",
    "sizeSmall": "Pequeno",
    "sizeMedium": "M\xE9dio",
    "sizeLarge": "Grande",
    "closeToTray": "Fechar na Bandeja",
    "minimizeToTray": "Minimizar para a bandeja",
    "fullScreen": "Tela Cheia",
    "searchingPid": "pesquisando...",
    "searchingEngine": "\u{1F50D} BUSCANDO MOTOR...",
    "activeEngine": "\u2714\uFE0F ATIVO (SQLite)",
    "subtitle": "Motor Rust e SQLite \u2022 Suporte a m\xFAltiplos projetos",
    "themeDark": "Escuro",
    "themeLight": "Claro",
    "themeHighContrast": "Alto",
    "themeSystem": "Sis",
    "noTaskSelected": "Selecione uma tarefa antes de iniciar o contador."
  }
};
