// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectComputedMetrics } from "./ProjectComputedMetrics";
import type { TaskComputedMetrics } from "./TaskComputedMetrics";

export type EngineComputedMetrics = { snapshotNowIso: string, tasks: { [key in string]?: TaskComputedMetrics }, projects: { [key in string]?: ProjectComputedMetrics }, };
