// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrontendEvent = "tray-set-gui-variant" | "tray-toggle-on-top" | "tray-stop-all-timers" | "native-close-requested" | "native-window-maximized" | "native-window-restored" | "native-window-minimized" | "native-window-resized";
