// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchLog = { id: string, projectId: string, taskId?: string, startTime: string, endTime: string, patchNote: string, isSystemEvent?: boolean, };
