// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersistenceCommand = "get_timer_state" | "add_project" | "toggle_project_archive" | "add_task" | "rename_project" | "rename_task" | "delete_task" | "toggle_task_complete" | "reset_database" | "get_settings" | "save_settings";
