// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectsPersistenceCommand = "add_project" | "rename_project" | "toggle_project_archive";
