// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectEditHistory } from "./ProjectEditHistory";

export type Project = { id: string, name: string, color: string, createdAt: string, archived?: boolean, originalName?: string, originalColor?: string, editHistory?: Array<ProjectEditHistory>, };
