// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskEditHistory } from "./TaskEditHistory";

export type Task = { id: string, projectId: string, parentTaskId?: string, name: string, createdAt: string, completed: boolean, originalName?: string, originalCompleted?: boolean, editHistory?: Array<TaskEditHistory>, };
