// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TasksPersistenceCommand = "add_task" | "rename_task" | "delete_task" | "toggle_task_complete";
