// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowCommand = "resize_window" | "set_gui_size" | "set_always_on_top" | "minimize_window" | "close_window" | "hide_window" | "show_window" | "set_window_resizable";
