// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ElapsedRangeFilter = { taskId?: string, projectId?: string, startDate?: string, endDate?: string, nowIso?: string, };
