// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineCommand = "start_timer" | "stop_timer" | "resume_timer" | "get_active_logs" | "get_task_elapsed" | "get_project_elapsed" | "get_elapsed_range" | "edit_time_log" | "get_project_statistics";
