// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HolidayType } from "./HolidayType";

export type HolidayLeaveEditHistory = { editedAt: string, prevName?: string, prevDate?: string, prevType?: HolidayType, reason?: string, };
