// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HolidayLeaveEditHistory } from "./HolidayLeaveEditHistory";
import type { HolidayType } from "./HolidayType";

export type HolidayLeave = { id: string, date: string, type: HolidayType, name: string, note?: string, originalName?: string, originalDate?: string, originalType?: HolidayType, editHistory?: Array<HolidayLeaveEditHistory>, };
