// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectEditHistory = { editedAt: string, prevName?: string, prevColor?: string, reason?: string, };
