// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectComputedMetrics = { projectId: string, totalElapsedSeconds: bigint, todayElapsedSeconds: bigint, thisWeekElapsedSeconds: bigint, activeTaskCount: number, completedTaskCount: number, isRunning: boolean, };
