// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SinkType } from "./SinkType";

export type Settings = { autoStart: boolean, autoPauseOnSleep: boolean, includePatchesInReports: boolean, activeSinks: Array<SinkType>, theme?: string, textAndIconSize?: string, guiVariant?: string, alwaysOnTopSmall?: boolean, alwaysOnTopMain?: boolean, minimizeToTray?: boolean, };
