// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskEditHistory = { editedAt: string, prevName?: string, prevCompleted?: boolean, reason?: string, };
