// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskComputedMetrics = { taskId: string, elapsedSeconds: number, selfElapsedSeconds: number, isRunning: boolean, hasRunningChild: boolean, };
