// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { Task } from "./Task";
import type { TimeLog } from "./TimeLog";

export type TimerRepositoryState = { projects: Array<Project>, tasks: Array<Task>, logs: Array<TimeLog>, activeLog: TimeLog | null, };
