// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeLogEditHistory } from "./TimeLogEditHistory";

export type TimeLog = { id: string, taskId: string, projectId: string, startTime: string, endTime?: string, note?: string, editHistory?: Array<TimeLogEditHistory>, };
