// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowCommand = "resize" | "set_size" | "set_always_on_top" | "minimize" | "close" | "hide" | "show" | "set_resizable";
